// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.6.1
// source: base_modifier.proto

package deadlock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MODIFIER_ENTRY_TYPE int32

const (
	MODIFIER_ENTRY_TYPE_MODIFIER_ENTRY_TYPE_ACTIVE  MODIFIER_ENTRY_TYPE = 1
	MODIFIER_ENTRY_TYPE_MODIFIER_ENTRY_TYPE_REMOVED MODIFIER_ENTRY_TYPE = 2
)

// Enum value maps for MODIFIER_ENTRY_TYPE.
var (
	MODIFIER_ENTRY_TYPE_name = map[int32]string{
		1: "MODIFIER_ENTRY_TYPE_ACTIVE",
		2: "MODIFIER_ENTRY_TYPE_REMOVED",
	}
	MODIFIER_ENTRY_TYPE_value = map[string]int32{
		"MODIFIER_ENTRY_TYPE_ACTIVE":  1,
		"MODIFIER_ENTRY_TYPE_REMOVED": 2,
	}
)

func (x MODIFIER_ENTRY_TYPE) Enum() *MODIFIER_ENTRY_TYPE {
	p := new(MODIFIER_ENTRY_TYPE)
	*p = x
	return p
}

func (x MODIFIER_ENTRY_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MODIFIER_ENTRY_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_base_modifier_proto_enumTypes[0].Descriptor()
}

func (MODIFIER_ENTRY_TYPE) Type() protoreflect.EnumType {
	return &file_base_modifier_proto_enumTypes[0]
}

func (x MODIFIER_ENTRY_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MODIFIER_ENTRY_TYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MODIFIER_ENTRY_TYPE(num)
	return nil
}

// Deprecated: Use MODIFIER_ENTRY_TYPE.Descriptor instead.
func (MODIFIER_ENTRY_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_base_modifier_proto_rawDescGZIP(), []int{0}
}

type CModifierTableEntry struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	EntryType                *MODIFIER_ENTRY_TYPE   `protobuf:"varint,1,req,name=entry_type,json=entryType,enum=deadlock.MODIFIER_ENTRY_TYPE,def=1" json:"entry_type,omitempty"`
	Parent                   *uint32                `protobuf:"varint,2,req,name=parent,def=16777215" json:"parent,omitempty"`
	SerialNumber             *uint32                `protobuf:"varint,3,req,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	ModifierSubclass         *uint32                `protobuf:"varint,4,opt,name=modifier_subclass,json=modifierSubclass" json:"modifier_subclass,omitempty"`
	StackCount               *int32                 `protobuf:"varint,5,opt,name=stack_count,json=stackCount" json:"stack_count,omitempty"`
	MaxStackCount            *int32                 `protobuf:"varint,6,opt,name=max_stack_count,json=maxStackCount" json:"max_stack_count,omitempty"`
	LastAppliedTime          *float32               `protobuf:"fixed32,7,opt,name=last_applied_time,json=lastAppliedTime" json:"last_applied_time,omitempty"`
	Duration                 *float32               `protobuf:"fixed32,8,opt,name=duration,def=-1" json:"duration,omitempty"`
	Caster                   *uint32                `protobuf:"varint,9,opt,name=caster,def=16777215" json:"caster,omitempty"`
	Ability                  *uint32                `protobuf:"varint,10,opt,name=ability,def=16777215" json:"ability,omitempty"`
	AuraProviderSerialNumber *int32                 `protobuf:"varint,11,opt,name=aura_provider_serial_number,json=auraProviderSerialNumber" json:"aura_provider_serial_number,omitempty"`
	AuraProviderEhandle      *uint32                `protobuf:"varint,12,opt,name=aura_provider_ehandle,json=auraProviderEhandle,def=16777215" json:"aura_provider_ehandle,omitempty"`
	AbilitySubclass          *uint32                `protobuf:"varint,13,opt,name=ability_subclass,json=abilitySubclass" json:"ability_subclass,omitempty"`
	InAuraRange              *bool                  `protobuf:"varint,14,opt,name=in_aura_range,json=inAuraRange" json:"in_aura_range,omitempty"`
	Bool1_                   *bool                  `protobuf:"varint,20,opt,name=bool1_,json=bool1" json:"bool1_,omitempty"`
	Bool2_                   *bool                  `protobuf:"varint,21,opt,name=bool2_,json=bool2" json:"bool2_,omitempty"`
	Bool3_                   *bool                  `protobuf:"varint,22,opt,name=bool3_,json=bool3" json:"bool3_,omitempty"`
	Bool4_                   *bool                  `protobuf:"varint,23,opt,name=bool4_,json=bool4" json:"bool4_,omitempty"`
	Int1_                    *int32                 `protobuf:"varint,25,opt,name=int1_,json=int1" json:"int1_,omitempty"`
	Int2_                    *int32                 `protobuf:"varint,26,opt,name=int2_,json=int2" json:"int2_,omitempty"`
	Int3_                    *int32                 `protobuf:"varint,27,opt,name=int3_,json=int3" json:"int3_,omitempty"`
	Int4_                    *int32                 `protobuf:"varint,28,opt,name=int4_,json=int4" json:"int4_,omitempty"`
	Float1_                  *float32               `protobuf:"fixed32,30,opt,name=float1_,json=float1" json:"float1_,omitempty"`
	Float2_                  *float32               `protobuf:"fixed32,31,opt,name=float2_,json=float2" json:"float2_,omitempty"`
	Float3_                  *float32               `protobuf:"fixed32,32,opt,name=float3_,json=float3" json:"float3_,omitempty"`
	Float4_                  *float32               `protobuf:"fixed32,33,opt,name=float4_,json=float4" json:"float4_,omitempty"`
	Float5_                  *float32               `protobuf:"fixed32,49,opt,name=float5_,json=float5" json:"float5_,omitempty"`
	Float6_                  *float32               `protobuf:"fixed32,50,opt,name=float6_,json=float6" json:"float6_,omitempty"`
	Float7_                  *float32               `protobuf:"fixed32,51,opt,name=float7_,json=float7" json:"float7_,omitempty"`
	Float8_                  *float32               `protobuf:"fixed32,52,opt,name=float8_,json=float8" json:"float8_,omitempty"`
	Float9_                  *float32               `protobuf:"fixed32,53,opt,name=float9_,json=float9" json:"float9_,omitempty"`
	Float10_                 *float32               `protobuf:"fixed32,54,opt,name=float10_,json=float10" json:"float10_,omitempty"`
	Uint1_                   *uint64                `protobuf:"varint,35,opt,name=uint1_,json=uint1" json:"uint1_,omitempty"`
	Uint2_                   *uint64                `protobuf:"varint,36,opt,name=uint2_,json=uint2" json:"uint2_,omitempty"`
	Uint3_                   *uint64                `protobuf:"varint,37,opt,name=uint3_,json=uint3" json:"uint3_,omitempty"`
	Uint4_                   *uint64                `protobuf:"varint,38,opt,name=uint4_,json=uint4" json:"uint4_,omitempty"`
	Vec1_                    *CMsgVector            `protobuf:"bytes,40,opt,name=vec1_,json=vec1" json:"vec1_,omitempty"`
	Vec2_                    *CMsgVector            `protobuf:"bytes,41,opt,name=vec2_,json=vec2" json:"vec2_,omitempty"`
	Vec3_                    *CMsgVector            `protobuf:"bytes,42,opt,name=vec3_,json=vec3" json:"vec3_,omitempty"`
	Vec4_                    *CMsgVector            `protobuf:"bytes,43,opt,name=vec4_,json=vec4" json:"vec4_,omitempty"`
	String1_                 *string                `protobuf:"bytes,45,opt,name=string1_,json=string1" json:"string1_,omitempty"`
	String2_                 *string                `protobuf:"bytes,46,opt,name=string2_,json=string2" json:"string2_,omitempty"`
	String3_                 *string                `protobuf:"bytes,47,opt,name=string3_,json=string3" json:"string3_,omitempty"`
	String4_                 *string                `protobuf:"bytes,48,opt,name=string4_,json=string4" json:"string4_,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

// Default values for CModifierTableEntry fields.
const (
	Default_CModifierTableEntry_EntryType           = MODIFIER_ENTRY_TYPE_MODIFIER_ENTRY_TYPE_ACTIVE
	Default_CModifierTableEntry_Parent              = uint32(16777215)
	Default_CModifierTableEntry_Duration            = float32(-1)
	Default_CModifierTableEntry_Caster              = uint32(16777215)
	Default_CModifierTableEntry_Ability             = uint32(16777215)
	Default_CModifierTableEntry_AuraProviderEhandle = uint32(16777215)
)

func (x *CModifierTableEntry) Reset() {
	*x = CModifierTableEntry{}
	mi := &file_base_modifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CModifierTableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CModifierTableEntry) ProtoMessage() {}

func (x *CModifierTableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_base_modifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CModifierTableEntry.ProtoReflect.Descriptor instead.
func (*CModifierTableEntry) Descriptor() ([]byte, []int) {
	return file_base_modifier_proto_rawDescGZIP(), []int{0}
}

func (x *CModifierTableEntry) GetEntryType() MODIFIER_ENTRY_TYPE {
	if x != nil && x.EntryType != nil {
		return *x.EntryType
	}
	return Default_CModifierTableEntry_EntryType
}

func (x *CModifierTableEntry) GetParent() uint32 {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return Default_CModifierTableEntry_Parent
}

func (x *CModifierTableEntry) GetSerialNumber() uint32 {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return 0
}

func (x *CModifierTableEntry) GetModifierSubclass() uint32 {
	if x != nil && x.ModifierSubclass != nil {
		return *x.ModifierSubclass
	}
	return 0
}

func (x *CModifierTableEntry) GetStackCount() int32 {
	if x != nil && x.StackCount != nil {
		return *x.StackCount
	}
	return 0
}

func (x *CModifierTableEntry) GetMaxStackCount() int32 {
	if x != nil && x.MaxStackCount != nil {
		return *x.MaxStackCount
	}
	return 0
}

func (x *CModifierTableEntry) GetLastAppliedTime() float32 {
	if x != nil && x.LastAppliedTime != nil {
		return *x.LastAppliedTime
	}
	return 0
}

func (x *CModifierTableEntry) GetDuration() float32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return Default_CModifierTableEntry_Duration
}

func (x *CModifierTableEntry) GetCaster() uint32 {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return Default_CModifierTableEntry_Caster
}

func (x *CModifierTableEntry) GetAbility() uint32 {
	if x != nil && x.Ability != nil {
		return *x.Ability
	}
	return Default_CModifierTableEntry_Ability
}

func (x *CModifierTableEntry) GetAuraProviderSerialNumber() int32 {
	if x != nil && x.AuraProviderSerialNumber != nil {
		return *x.AuraProviderSerialNumber
	}
	return 0
}

func (x *CModifierTableEntry) GetAuraProviderEhandle() uint32 {
	if x != nil && x.AuraProviderEhandle != nil {
		return *x.AuraProviderEhandle
	}
	return Default_CModifierTableEntry_AuraProviderEhandle
}

func (x *CModifierTableEntry) GetAbilitySubclass() uint32 {
	if x != nil && x.AbilitySubclass != nil {
		return *x.AbilitySubclass
	}
	return 0
}

func (x *CModifierTableEntry) GetInAuraRange() bool {
	if x != nil && x.InAuraRange != nil {
		return *x.InAuraRange
	}
	return false
}

func (x *CModifierTableEntry) GetBool1_() bool {
	if x != nil && x.Bool1_ != nil {
		return *x.Bool1_
	}
	return false
}

func (x *CModifierTableEntry) GetBool2_() bool {
	if x != nil && x.Bool2_ != nil {
		return *x.Bool2_
	}
	return false
}

func (x *CModifierTableEntry) GetBool3_() bool {
	if x != nil && x.Bool3_ != nil {
		return *x.Bool3_
	}
	return false
}

func (x *CModifierTableEntry) GetBool4_() bool {
	if x != nil && x.Bool4_ != nil {
		return *x.Bool4_
	}
	return false
}

func (x *CModifierTableEntry) GetInt1_() int32 {
	if x != nil && x.Int1_ != nil {
		return *x.Int1_
	}
	return 0
}

func (x *CModifierTableEntry) GetInt2_() int32 {
	if x != nil && x.Int2_ != nil {
		return *x.Int2_
	}
	return 0
}

func (x *CModifierTableEntry) GetInt3_() int32 {
	if x != nil && x.Int3_ != nil {
		return *x.Int3_
	}
	return 0
}

func (x *CModifierTableEntry) GetInt4_() int32 {
	if x != nil && x.Int4_ != nil {
		return *x.Int4_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat1_() float32 {
	if x != nil && x.Float1_ != nil {
		return *x.Float1_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat2_() float32 {
	if x != nil && x.Float2_ != nil {
		return *x.Float2_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat3_() float32 {
	if x != nil && x.Float3_ != nil {
		return *x.Float3_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat4_() float32 {
	if x != nil && x.Float4_ != nil {
		return *x.Float4_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat5_() float32 {
	if x != nil && x.Float5_ != nil {
		return *x.Float5_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat6_() float32 {
	if x != nil && x.Float6_ != nil {
		return *x.Float6_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat7_() float32 {
	if x != nil && x.Float7_ != nil {
		return *x.Float7_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat8_() float32 {
	if x != nil && x.Float8_ != nil {
		return *x.Float8_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat9_() float32 {
	if x != nil && x.Float9_ != nil {
		return *x.Float9_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat10_() float32 {
	if x != nil && x.Float10_ != nil {
		return *x.Float10_
	}
	return 0
}

func (x *CModifierTableEntry) GetUint1_() uint64 {
	if x != nil && x.Uint1_ != nil {
		return *x.Uint1_
	}
	return 0
}

func (x *CModifierTableEntry) GetUint2_() uint64 {
	if x != nil && x.Uint2_ != nil {
		return *x.Uint2_
	}
	return 0
}

func (x *CModifierTableEntry) GetUint3_() uint64 {
	if x != nil && x.Uint3_ != nil {
		return *x.Uint3_
	}
	return 0
}

func (x *CModifierTableEntry) GetUint4_() uint64 {
	if x != nil && x.Uint4_ != nil {
		return *x.Uint4_
	}
	return 0
}

func (x *CModifierTableEntry) GetVec1_() *CMsgVector {
	if x != nil {
		return x.Vec1_
	}
	return nil
}

func (x *CModifierTableEntry) GetVec2_() *CMsgVector {
	if x != nil {
		return x.Vec2_
	}
	return nil
}

func (x *CModifierTableEntry) GetVec3_() *CMsgVector {
	if x != nil {
		return x.Vec3_
	}
	return nil
}

func (x *CModifierTableEntry) GetVec4_() *CMsgVector {
	if x != nil {
		return x.Vec4_
	}
	return nil
}

func (x *CModifierTableEntry) GetString1_() string {
	if x != nil && x.String1_ != nil {
		return *x.String1_
	}
	return ""
}

func (x *CModifierTableEntry) GetString2_() string {
	if x != nil && x.String2_ != nil {
		return *x.String2_
	}
	return ""
}

func (x *CModifierTableEntry) GetString3_() string {
	if x != nil && x.String3_ != nil {
		return *x.String3_
	}
	return ""
}

func (x *CModifierTableEntry) GetString4_() string {
	if x != nil && x.String4_ != nil {
		return *x.String4_
	}
	return ""
}

var File_base_modifier_proto protoreflect.FileDescriptor

const file_base_modifier_proto_rawDesc = "" +
	"\n" +
	"\x13base_modifier.proto\x12\bdeadlock\x1a\x16networkbasetypes.proto\"\xaa\v\n" +
	"\x13CModifierTableEntry\x12X\n" +
	"\n" +
	"entry_type\x18\x01 \x02(\x0e2\x1d.deadlock.MODIFIER_ENTRY_TYPE:\x1aMODIFIER_ENTRY_TYPE_ACTIVER\tentryType\x12 \n" +
	"\x06parent\x18\x02 \x02(\r:\b16777215R\x06parent\x12#\n" +
	"\rserial_number\x18\x03 \x02(\rR\fserialNumber\x12+\n" +
	"\x11modifier_subclass\x18\x04 \x01(\rR\x10modifierSubclass\x12\x1f\n" +
	"\vstack_count\x18\x05 \x01(\x05R\n" +
	"stackCount\x12&\n" +
	"\x0fmax_stack_count\x18\x06 \x01(\x05R\rmaxStackCount\x12*\n" +
	"\x11last_applied_time\x18\a \x01(\x02R\x0flastAppliedTime\x12\x1e\n" +
	"\bduration\x18\b \x01(\x02:\x02-1R\bduration\x12 \n" +
	"\x06caster\x18\t \x01(\r:\b16777215R\x06caster\x12\"\n" +
	"\aability\x18\n" +
	" \x01(\r:\b16777215R\aability\x12=\n" +
	"\x1baura_provider_serial_number\x18\v \x01(\x05R\x18auraProviderSerialNumber\x12<\n" +
	"\x15aura_provider_ehandle\x18\f \x01(\r:\b16777215R\x13auraProviderEhandle\x12)\n" +
	"\x10ability_subclass\x18\r \x01(\rR\x0fabilitySubclass\x12\"\n" +
	"\rin_aura_range\x18\x0e \x01(\bR\vinAuraRange\x12\x15\n" +
	"\x06bool1_\x18\x14 \x01(\bR\x05bool1\x12\x15\n" +
	"\x06bool2_\x18\x15 \x01(\bR\x05bool2\x12\x15\n" +
	"\x06bool3_\x18\x16 \x01(\bR\x05bool3\x12\x15\n" +
	"\x06bool4_\x18\x17 \x01(\bR\x05bool4\x12\x13\n" +
	"\x05int1_\x18\x19 \x01(\x05R\x04int1\x12\x13\n" +
	"\x05int2_\x18\x1a \x01(\x05R\x04int2\x12\x13\n" +
	"\x05int3_\x18\x1b \x01(\x05R\x04int3\x12\x13\n" +
	"\x05int4_\x18\x1c \x01(\x05R\x04int4\x12\x17\n" +
	"\afloat1_\x18\x1e \x01(\x02R\x06float1\x12\x17\n" +
	"\afloat2_\x18\x1f \x01(\x02R\x06float2\x12\x17\n" +
	"\afloat3_\x18  \x01(\x02R\x06float3\x12\x17\n" +
	"\afloat4_\x18! \x01(\x02R\x06float4\x12\x17\n" +
	"\afloat5_\x181 \x01(\x02R\x06float5\x12\x17\n" +
	"\afloat6_\x182 \x01(\x02R\x06float6\x12\x17\n" +
	"\afloat7_\x183 \x01(\x02R\x06float7\x12\x17\n" +
	"\afloat8_\x184 \x01(\x02R\x06float8\x12\x17\n" +
	"\afloat9_\x185 \x01(\x02R\x06float9\x12\x19\n" +
	"\bfloat10_\x186 \x01(\x02R\afloat10\x12\x15\n" +
	"\x06uint1_\x18# \x01(\x04R\x05uint1\x12\x15\n" +
	"\x06uint2_\x18$ \x01(\x04R\x05uint2\x12\x15\n" +
	"\x06uint3_\x18% \x01(\x04R\x05uint3\x12\x15\n" +
	"\x06uint4_\x18& \x01(\x04R\x05uint4\x12)\n" +
	"\x05vec1_\x18( \x01(\v2\x14.deadlock.CMsgVectorR\x04vec1\x12)\n" +
	"\x05vec2_\x18) \x01(\v2\x14.deadlock.CMsgVectorR\x04vec2\x12)\n" +
	"\x05vec3_\x18* \x01(\v2\x14.deadlock.CMsgVectorR\x04vec3\x12)\n" +
	"\x05vec4_\x18+ \x01(\v2\x14.deadlock.CMsgVectorR\x04vec4\x12\x19\n" +
	"\bstring1_\x18- \x01(\tR\astring1\x12\x19\n" +
	"\bstring2_\x18. \x01(\tR\astring2\x12\x19\n" +
	"\bstring3_\x18/ \x01(\tR\astring3\x12\x19\n" +
	"\bstring4_\x180 \x01(\tR\astring4*V\n" +
	"\x13MODIFIER_ENTRY_TYPE\x12\x1e\n" +
	"\x1aMODIFIER_ENTRY_TYPE_ACTIVE\x10\x01\x12\x1f\n" +
	"\x1bMODIFIER_ENTRY_TYPE_REMOVED\x10\x02B4Z2github.com/RyPort/paradox-parser/deadlock;deadlock"

var (
	file_base_modifier_proto_rawDescOnce sync.Once
	file_base_modifier_proto_rawDescData []byte
)

func file_base_modifier_proto_rawDescGZIP() []byte {
	file_base_modifier_proto_rawDescOnce.Do(func() {
		file_base_modifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_modifier_proto_rawDesc), len(file_base_modifier_proto_rawDesc)))
	})
	return file_base_modifier_proto_rawDescData
}

var file_base_modifier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_base_modifier_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_base_modifier_proto_goTypes = []any{
	(MODIFIER_ENTRY_TYPE)(0),    // 0: deadlock.MODIFIER_ENTRY_TYPE
	(*CModifierTableEntry)(nil), // 1: deadlock.CModifierTableEntry
	(*CMsgVector)(nil),          // 2: deadlock.CMsgVector
}
var file_base_modifier_proto_depIdxs = []int32{
	0, // 0: deadlock.CModifierTableEntry.entry_type:type_name -> deadlock.MODIFIER_ENTRY_TYPE
	2, // 1: deadlock.CModifierTableEntry.vec1_:type_name -> deadlock.CMsgVector
	2, // 2: deadlock.CModifierTableEntry.vec2_:type_name -> deadlock.CMsgVector
	2, // 3: deadlock.CModifierTableEntry.vec3_:type_name -> deadlock.CMsgVector
	2, // 4: deadlock.CModifierTableEntry.vec4_:type_name -> deadlock.CMsgVector
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_base_modifier_proto_init() }
func file_base_modifier_proto_init() {
	if File_base_modifier_proto != nil {
		return
	}
	file_networkbasetypes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_modifier_proto_rawDesc), len(file_base_modifier_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_modifier_proto_goTypes,
		DependencyIndexes: file_base_modifier_proto_depIdxs,
		EnumInfos:         file_base_modifier_proto_enumTypes,
		MessageInfos:      file_base_modifier_proto_msgTypes,
	}.Build()
	File_base_modifier_proto = out.File
	file_base_modifier_proto_goTypes = nil
	file_base_modifier_proto_depIdxs = nil
}
