// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.6.1
// source: citadel_gameevents.proto

package deadlock

import (
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ECitadelGameEvents int32

const (
	ECitadelGameEvents_GE_FireBullets            ECitadelGameEvents = 450
	ECitadelGameEvents_GE_PlayerAnimEvent        ECitadelGameEvents = 451
	ECitadelGameEvents_GE_ParticleSystemManager  ECitadelGameEvents = 458
	ECitadelGameEvents_GE_ScreenTextPretty       ECitadelGameEvents = 459
	ECitadelGameEvents_GE_BulletImpact           ECitadelGameEvents = 461
	ECitadelGameEvents_GE_EnableSatVolumesEvent  ECitadelGameEvents = 462
	ECitadelGameEvents_GE_PlaceSatVolumeEvent    ECitadelGameEvents = 463
	ECitadelGameEvents_GE_DisableSatVolumesEvent ECitadelGameEvents = 464
	ECitadelGameEvents_GE_RemoveSatVolumeEvent   ECitadelGameEvents = 465
	ECitadelGameEvents_GE_RemoveBullet           ECitadelGameEvents = 466
)

// Enum value maps for ECitadelGameEvents.
var (
	ECitadelGameEvents_name = map[int32]string{
		450: "GE_FireBullets",
		451: "GE_PlayerAnimEvent",
		458: "GE_ParticleSystemManager",
		459: "GE_ScreenTextPretty",
		461: "GE_BulletImpact",
		462: "GE_EnableSatVolumesEvent",
		463: "GE_PlaceSatVolumeEvent",
		464: "GE_DisableSatVolumesEvent",
		465: "GE_RemoveSatVolumeEvent",
		466: "GE_RemoveBullet",
	}
	ECitadelGameEvents_value = map[string]int32{
		"GE_FireBullets":            450,
		"GE_PlayerAnimEvent":        451,
		"GE_ParticleSystemManager":  458,
		"GE_ScreenTextPretty":       459,
		"GE_BulletImpact":           461,
		"GE_EnableSatVolumesEvent":  462,
		"GE_PlaceSatVolumeEvent":    463,
		"GE_DisableSatVolumesEvent": 464,
		"GE_RemoveSatVolumeEvent":   465,
		"GE_RemoveBullet":           466,
	}
)

func (x ECitadelGameEvents) Enum() *ECitadelGameEvents {
	p := new(ECitadelGameEvents)
	*p = x
	return p
}

func (x ECitadelGameEvents) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECitadelGameEvents) Descriptor() protoreflect.EnumDescriptor {
	return file_citadel_gameevents_proto_enumTypes[0].Descriptor()
}

func (ECitadelGameEvents) Type() protoreflect.EnumType {
	return &file_citadel_gameevents_proto_enumTypes[0]
}

func (x ECitadelGameEvents) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ECitadelGameEvents) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ECitadelGameEvents(num)
	return nil
}

// Deprecated: Use ECitadelGameEvents.Descriptor instead.
func (ECitadelGameEvents) EnumDescriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{0}
}

type PARTICLE_SYSTEM_MANAGER_MESSAGE int32

const (
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_CREATE             PARTICLE_SYSTEM_MANAGER_MESSAGE = 0
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_DESTROY            PARTICLE_SYSTEM_MANAGER_MESSAGE = 1
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_DESTROY_INVOLVING  PARTICLE_SYSTEM_MANAGER_MESSAGE = 2
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_RELEASE            PARTICLE_SYSTEM_MANAGER_MESSAGE = 3
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE             PARTICLE_SYSTEM_MANAGER_MESSAGE = 4
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FORWARD     PARTICLE_SYSTEM_MANAGER_MESSAGE = 5
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_ORIENTATION PARTICLE_SYSTEM_MANAGER_MESSAGE = 6
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FALLBACK    PARTICLE_SYSTEM_MANAGER_MESSAGE = 7
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_ENT         PARTICLE_SYSTEM_MANAGER_MESSAGE = 8
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_OFFSET      PARTICLE_SYSTEM_MANAGER_MESSAGE = 9
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FROZEN      PARTICLE_SYSTEM_MANAGER_MESSAGE = 10
	PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_SHOULD_DRAW PARTICLE_SYSTEM_MANAGER_MESSAGE = 11
)

// Enum value maps for PARTICLE_SYSTEM_MANAGER_MESSAGE.
var (
	PARTICLE_SYSTEM_MANAGER_MESSAGE_name = map[int32]string{
		0:  "PARTICLE_SYSTEM_MANAGER_EVENT_CREATE",
		1:  "PARTICLE_SYSTEM_MANAGER_EVENT_DESTROY",
		2:  "PARTICLE_SYSTEM_MANAGER_EVENT_DESTROY_INVOLVING",
		3:  "PARTICLE_SYSTEM_MANAGER_EVENT_RELEASE",
		4:  "PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE",
		5:  "PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FORWARD",
		6:  "PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_ORIENTATION",
		7:  "PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FALLBACK",
		8:  "PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_ENT",
		9:  "PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_OFFSET",
		10: "PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FROZEN",
		11: "PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_SHOULD_DRAW",
	}
	PARTICLE_SYSTEM_MANAGER_MESSAGE_value = map[string]int32{
		"PARTICLE_SYSTEM_MANAGER_EVENT_CREATE":             0,
		"PARTICLE_SYSTEM_MANAGER_EVENT_DESTROY":            1,
		"PARTICLE_SYSTEM_MANAGER_EVENT_DESTROY_INVOLVING":  2,
		"PARTICLE_SYSTEM_MANAGER_EVENT_RELEASE":            3,
		"PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE":             4,
		"PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FORWARD":     5,
		"PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_ORIENTATION": 6,
		"PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FALLBACK":    7,
		"PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_ENT":         8,
		"PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_OFFSET":      9,
		"PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FROZEN":      10,
		"PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_SHOULD_DRAW": 11,
	}
)

func (x PARTICLE_SYSTEM_MANAGER_MESSAGE) Enum() *PARTICLE_SYSTEM_MANAGER_MESSAGE {
	p := new(PARTICLE_SYSTEM_MANAGER_MESSAGE)
	*p = x
	return p
}

func (x PARTICLE_SYSTEM_MANAGER_MESSAGE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PARTICLE_SYSTEM_MANAGER_MESSAGE) Descriptor() protoreflect.EnumDescriptor {
	return file_citadel_gameevents_proto_enumTypes[1].Descriptor()
}

func (PARTICLE_SYSTEM_MANAGER_MESSAGE) Type() protoreflect.EnumType {
	return &file_citadel_gameevents_proto_enumTypes[1]
}

func (x PARTICLE_SYSTEM_MANAGER_MESSAGE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PARTICLE_SYSTEM_MANAGER_MESSAGE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PARTICLE_SYSTEM_MANAGER_MESSAGE(num)
	return nil
}

// Deprecated: Use PARTICLE_SYSTEM_MANAGER_MESSAGE.Descriptor instead.
func (PARTICLE_SYSTEM_MANAGER_MESSAGE) EnumDescriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{1}
}

type CMsgFireBullets struct {
	state                   protoimpl.MessageState              `protogen:"open.v1"`
	Origin                  *CMsgVector                         `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Angles                  *CMsgQAngle                         `protobuf:"bytes,2,opt,name=angles" json:"angles,omitempty"`
	Seed                    *uint32                             `protobuf:"varint,4,opt,name=seed" json:"seed,omitempty"`
	ShooterEntity           *int32                              `protobuf:"varint,5,opt,name=shooter_entity,json=shooterEntity,def=-1" json:"shooter_entity,omitempty"`
	Ability                 *int32                              `protobuf:"varint,7,opt,name=ability,def=-1" json:"ability,omitempty"`
	PenetrationPercent      *float32                            `protobuf:"fixed32,8,opt,name=penetration_percent,json=penetrationPercent" json:"penetration_percent,omitempty"`
	Spread                  *float32                            `protobuf:"fixed32,9,opt,name=spread" json:"spread,omitempty"`
	FiredFromGun            *bool                               `protobuf:"varint,10,opt,name=fired_from_gun,json=firedFromGun,def=1" json:"fired_from_gun,omitempty"`
	BulletsOverride         *uint32                             `protobuf:"varint,11,opt,name=bullets_override,json=bulletsOverride" json:"bullets_override,omitempty"`
	TracerReplacement       *CMsgFireBullets_TracerAssignment   `protobuf:"bytes,12,opt,name=tracer_replacement,json=tracerReplacement" json:"tracer_replacement,omitempty"`
	TracerAdditional        []*CMsgFireBullets_TracerAssignment `protobuf:"bytes,13,rep,name=tracer_additional,json=tracerAdditional" json:"tracer_additional,omitempty"`
	AnglesOriginal          *CMsgQAngle                         `protobuf:"bytes,14,opt,name=angles_original,json=anglesOriginal" json:"angles_original,omitempty"`
	WeaponSubclassId        *uint32                             `protobuf:"varint,15,opt,name=weapon_subclass_id,json=weaponSubclassId" json:"weapon_subclass_id,omitempty"`
	ShotNumber              *uint32                             `protobuf:"varint,16,opt,name=shot_number,json=shotNumber" json:"shot_number,omitempty"`
	IgnoreEntity            *int32                              `protobuf:"varint,17,opt,name=ignore_entity,json=ignoreEntity,def=-1" json:"ignore_entity,omitempty"`
	MaxRange                *float32                            `protobuf:"fixed32,18,opt,name=max_range,json=maxRange" json:"max_range,omitempty"`
	ShotId                  *uint32                             `protobuf:"varint,19,opt,name=shot_id,json=shotId" json:"shot_id,omitempty"`
	PredictHitsAgainstUnits *bool                               `protobuf:"varint,20,opt,name=predict_hits_against_units,json=predictHitsAgainstUnits,def=1" json:"predict_hits_against_units,omitempty"`
	BulletRadiusOverride    *float32                            `protobuf:"fixed32,21,opt,name=bullet_radius_override,json=bulletRadiusOverride,def=0" json:"bullet_radius_override,omitempty"`
	BulletSpeedOverride     *float32                            `protobuf:"fixed32,22,opt,name=bullet_speed_override,json=bulletSpeedOverride,def=0" json:"bullet_speed_override,omitempty"`
	BulletGravityOverride   *float32                            `protobuf:"fixed32,23,opt,name=bullet_gravity_override,json=bulletGravityOverride,def=0" json:"bullet_gravity_override,omitempty"`
	MuzzleNumber            *int32                              `protobuf:"varint,24,opt,name=muzzle_number,json=muzzleNumber" json:"muzzle_number,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

// Default values for CMsgFireBullets fields.
const (
	Default_CMsgFireBullets_ShooterEntity           = int32(-1)
	Default_CMsgFireBullets_Ability                 = int32(-1)
	Default_CMsgFireBullets_FiredFromGun            = bool(true)
	Default_CMsgFireBullets_IgnoreEntity            = int32(-1)
	Default_CMsgFireBullets_PredictHitsAgainstUnits = bool(true)
	Default_CMsgFireBullets_BulletRadiusOverride    = float32(0)
	Default_CMsgFireBullets_BulletSpeedOverride     = float32(0)
	Default_CMsgFireBullets_BulletGravityOverride   = float32(0)
)

func (x *CMsgFireBullets) Reset() {
	*x = CMsgFireBullets{}
	mi := &file_citadel_gameevents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgFireBullets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgFireBullets) ProtoMessage() {}

func (x *CMsgFireBullets) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgFireBullets.ProtoReflect.Descriptor instead.
func (*CMsgFireBullets) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgFireBullets) GetOrigin() *CMsgVector {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *CMsgFireBullets) GetAngles() *CMsgQAngle {
	if x != nil {
		return x.Angles
	}
	return nil
}

func (x *CMsgFireBullets) GetSeed() uint32 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *CMsgFireBullets) GetShooterEntity() int32 {
	if x != nil && x.ShooterEntity != nil {
		return *x.ShooterEntity
	}
	return Default_CMsgFireBullets_ShooterEntity
}

func (x *CMsgFireBullets) GetAbility() int32 {
	if x != nil && x.Ability != nil {
		return *x.Ability
	}
	return Default_CMsgFireBullets_Ability
}

func (x *CMsgFireBullets) GetPenetrationPercent() float32 {
	if x != nil && x.PenetrationPercent != nil {
		return *x.PenetrationPercent
	}
	return 0
}

func (x *CMsgFireBullets) GetSpread() float32 {
	if x != nil && x.Spread != nil {
		return *x.Spread
	}
	return 0
}

func (x *CMsgFireBullets) GetFiredFromGun() bool {
	if x != nil && x.FiredFromGun != nil {
		return *x.FiredFromGun
	}
	return Default_CMsgFireBullets_FiredFromGun
}

func (x *CMsgFireBullets) GetBulletsOverride() uint32 {
	if x != nil && x.BulletsOverride != nil {
		return *x.BulletsOverride
	}
	return 0
}

func (x *CMsgFireBullets) GetTracerReplacement() *CMsgFireBullets_TracerAssignment {
	if x != nil {
		return x.TracerReplacement
	}
	return nil
}

func (x *CMsgFireBullets) GetTracerAdditional() []*CMsgFireBullets_TracerAssignment {
	if x != nil {
		return x.TracerAdditional
	}
	return nil
}

func (x *CMsgFireBullets) GetAnglesOriginal() *CMsgQAngle {
	if x != nil {
		return x.AnglesOriginal
	}
	return nil
}

func (x *CMsgFireBullets) GetWeaponSubclassId() uint32 {
	if x != nil && x.WeaponSubclassId != nil {
		return *x.WeaponSubclassId
	}
	return 0
}

func (x *CMsgFireBullets) GetShotNumber() uint32 {
	if x != nil && x.ShotNumber != nil {
		return *x.ShotNumber
	}
	return 0
}

func (x *CMsgFireBullets) GetIgnoreEntity() int32 {
	if x != nil && x.IgnoreEntity != nil {
		return *x.IgnoreEntity
	}
	return Default_CMsgFireBullets_IgnoreEntity
}

func (x *CMsgFireBullets) GetMaxRange() float32 {
	if x != nil && x.MaxRange != nil {
		return *x.MaxRange
	}
	return 0
}

func (x *CMsgFireBullets) GetShotId() uint32 {
	if x != nil && x.ShotId != nil {
		return *x.ShotId
	}
	return 0
}

func (x *CMsgFireBullets) GetPredictHitsAgainstUnits() bool {
	if x != nil && x.PredictHitsAgainstUnits != nil {
		return *x.PredictHitsAgainstUnits
	}
	return Default_CMsgFireBullets_PredictHitsAgainstUnits
}

func (x *CMsgFireBullets) GetBulletRadiusOverride() float32 {
	if x != nil && x.BulletRadiusOverride != nil {
		return *x.BulletRadiusOverride
	}
	return Default_CMsgFireBullets_BulletRadiusOverride
}

func (x *CMsgFireBullets) GetBulletSpeedOverride() float32 {
	if x != nil && x.BulletSpeedOverride != nil {
		return *x.BulletSpeedOverride
	}
	return Default_CMsgFireBullets_BulletSpeedOverride
}

func (x *CMsgFireBullets) GetBulletGravityOverride() float32 {
	if x != nil && x.BulletGravityOverride != nil {
		return *x.BulletGravityOverride
	}
	return Default_CMsgFireBullets_BulletGravityOverride
}

func (x *CMsgFireBullets) GetMuzzleNumber() int32 {
	if x != nil && x.MuzzleNumber != nil {
		return *x.MuzzleNumber
	}
	return 0
}

type CMsgBulletImpact struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TraceStart        *CMsgVector            `protobuf:"bytes,1,opt,name=trace_start,json=traceStart" json:"trace_start,omitempty"`
	ImpactOrigin      *CMsgVector            `protobuf:"bytes,2,opt,name=impact_origin,json=impactOrigin" json:"impact_origin,omitempty"`
	SurfaceNormal     *CMsgVector            `protobuf:"bytes,3,opt,name=surface_normal,json=surfaceNormal" json:"surface_normal,omitempty"`
	Damage            *uint32                `protobuf:"varint,4,opt,name=damage" json:"damage,omitempty"`
	SurfaceType       *uint32                `protobuf:"varint,5,opt,name=surface_type,json=surfaceType" json:"surface_type,omitempty"`
	AbilityEhandle    *uint32                `protobuf:"varint,7,opt,name=ability_ehandle,json=abilityEhandle,def=16777215" json:"ability_ehandle,omitempty"`
	ImpactedEhandle   *uint32                `protobuf:"varint,8,opt,name=impacted_ehandle,json=impactedEhandle,def=16777215" json:"impacted_ehandle,omitempty"`
	ImpactedBoneIndex *uint32                `protobuf:"varint,9,opt,name=impacted_bone_index,json=impactedBoneIndex" json:"impacted_bone_index,omitempty"`
	WeaponSubclassId  *uint32                `protobuf:"varint,10,opt,name=weapon_subclass_id,json=weaponSubclassId" json:"weapon_subclass_id,omitempty"`
	ShooterEhandle    *uint32                `protobuf:"varint,11,opt,name=shooter_ehandle,json=shooterEhandle,def=16777215" json:"shooter_ehandle,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

// Default values for CMsgBulletImpact fields.
const (
	Default_CMsgBulletImpact_AbilityEhandle  = uint32(16777215)
	Default_CMsgBulletImpact_ImpactedEhandle = uint32(16777215)
	Default_CMsgBulletImpact_ShooterEhandle  = uint32(16777215)
)

func (x *CMsgBulletImpact) Reset() {
	*x = CMsgBulletImpact{}
	mi := &file_citadel_gameevents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgBulletImpact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgBulletImpact) ProtoMessage() {}

func (x *CMsgBulletImpact) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgBulletImpact.ProtoReflect.Descriptor instead.
func (*CMsgBulletImpact) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgBulletImpact) GetTraceStart() *CMsgVector {
	if x != nil {
		return x.TraceStart
	}
	return nil
}

func (x *CMsgBulletImpact) GetImpactOrigin() *CMsgVector {
	if x != nil {
		return x.ImpactOrigin
	}
	return nil
}

func (x *CMsgBulletImpact) GetSurfaceNormal() *CMsgVector {
	if x != nil {
		return x.SurfaceNormal
	}
	return nil
}

func (x *CMsgBulletImpact) GetDamage() uint32 {
	if x != nil && x.Damage != nil {
		return *x.Damage
	}
	return 0
}

func (x *CMsgBulletImpact) GetSurfaceType() uint32 {
	if x != nil && x.SurfaceType != nil {
		return *x.SurfaceType
	}
	return 0
}

func (x *CMsgBulletImpact) GetAbilityEhandle() uint32 {
	if x != nil && x.AbilityEhandle != nil {
		return *x.AbilityEhandle
	}
	return Default_CMsgBulletImpact_AbilityEhandle
}

func (x *CMsgBulletImpact) GetImpactedEhandle() uint32 {
	if x != nil && x.ImpactedEhandle != nil {
		return *x.ImpactedEhandle
	}
	return Default_CMsgBulletImpact_ImpactedEhandle
}

func (x *CMsgBulletImpact) GetImpactedBoneIndex() uint32 {
	if x != nil && x.ImpactedBoneIndex != nil {
		return *x.ImpactedBoneIndex
	}
	return 0
}

func (x *CMsgBulletImpact) GetWeaponSubclassId() uint32 {
	if x != nil && x.WeaponSubclassId != nil {
		return *x.WeaponSubclassId
	}
	return 0
}

func (x *CMsgBulletImpact) GetShooterEhandle() uint32 {
	if x != nil && x.ShooterEhandle != nil {
		return *x.ShooterEhandle
	}
	return Default_CMsgBulletImpact_ShooterEhandle
}

type CMsgPlayerAnimEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *uint32                `protobuf:"fixed32,1,opt,name=player,def=16777215" json:"player,omitempty"`
	Event         *uint32                `protobuf:"varint,2,opt,name=event" json:"event,omitempty"`
	Data          *int32                 `protobuf:"varint,3,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgPlayerAnimEvent fields.
const (
	Default_CMsgPlayerAnimEvent_Player = uint32(16777215)
)

func (x *CMsgPlayerAnimEvent) Reset() {
	*x = CMsgPlayerAnimEvent{}
	mi := &file_citadel_gameevents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgPlayerAnimEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgPlayerAnimEvent) ProtoMessage() {}

func (x *CMsgPlayerAnimEvent) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgPlayerAnimEvent.ProtoReflect.Descriptor instead.
func (*CMsgPlayerAnimEvent) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgPlayerAnimEvent) GetPlayer() uint32 {
	if x != nil && x.Player != nil {
		return *x.Player
	}
	return Default_CMsgPlayerAnimEvent_Player
}

func (x *CMsgPlayerAnimEvent) GetEvent() uint32 {
	if x != nil && x.Event != nil {
		return *x.Event
	}
	return 0
}

func (x *CMsgPlayerAnimEvent) GetData() int32 {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return 0
}

type CMsgParticleSystemManager struct {
	state                    protoimpl.MessageState                              `protogen:"open.v1"`
	Type                     *PARTICLE_SYSTEM_MANAGER_MESSAGE                    `protobuf:"varint,1,req,name=type,enum=deadlock.PARTICLE_SYSTEM_MANAGER_MESSAGE,def=0" json:"type,omitempty"`
	Index                    *uint32                                             `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	CreateParticle           *CMsgParticleSystemManager_CreateParticle           `protobuf:"bytes,3,opt,name=create_particle,json=createParticle" json:"create_particle,omitempty"`
	DestroyParticle          *CMsgParticleSystemManager_DestroyParticle          `protobuf:"bytes,4,opt,name=destroy_particle,json=destroyParticle" json:"destroy_particle,omitempty"`
	DestroyParticleInvolving *CMsgParticleSystemManager_DestroyParticleInvolving `protobuf:"bytes,5,opt,name=destroy_particle_involving,json=destroyParticleInvolving" json:"destroy_particle_involving,omitempty"`
	ReleaseParticleIndex     *CMsgParticleSystemManager_ReleaseParticleIndex     `protobuf:"bytes,6,opt,name=release_particle_index,json=releaseParticleIndex" json:"release_particle_index,omitempty"`
	UpdateParticle           *CMsgParticleSystemManager_UpdateParticle           `protobuf:"bytes,7,opt,name=update_particle,json=updateParticle" json:"update_particle,omitempty"`
	UpdateParticleFwd        *CMsgParticleSystemManager_UpdateParticleFwd        `protobuf:"bytes,8,opt,name=update_particle_fwd,json=updateParticleFwd" json:"update_particle_fwd,omitempty"`
	UpdateParticleOrient     *CMsgParticleSystemManager_UpdateParticleOrient     `protobuf:"bytes,9,opt,name=update_particle_orient,json=updateParticleOrient" json:"update_particle_orient,omitempty"`
	UpdateParticleFallback   *CMsgParticleSystemManager_UpdateParticleFallback   `protobuf:"bytes,10,opt,name=update_particle_fallback,json=updateParticleFallback" json:"update_particle_fallback,omitempty"`
	UpdateParticleOffset     *CMsgParticleSystemManager_UpdateParticleOffset     `protobuf:"bytes,11,opt,name=update_particle_offset,json=updateParticleOffset" json:"update_particle_offset,omitempty"`
	UpdateParticleEnt        *CMsgParticleSystemManager_UpdateParticleEnt        `protobuf:"bytes,12,opt,name=update_particle_ent,json=updateParticleEnt" json:"update_particle_ent,omitempty"`
	UpdateParticleFrozen     *CMsgParticleSystemManager_UpdateParticleFrozen     `protobuf:"bytes,13,opt,name=update_particle_frozen,json=updateParticleFrozen" json:"update_particle_frozen,omitempty"`
	UpdateParticleShouldDraw *CMsgParticleSystemManager_UpdateParticleShouldDraw `protobuf:"bytes,14,opt,name=update_particle_should_draw,json=updateParticleShouldDraw" json:"update_particle_should_draw,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

// Default values for CMsgParticleSystemManager fields.
const (
	Default_CMsgParticleSystemManager_Type = PARTICLE_SYSTEM_MANAGER_MESSAGE_PARTICLE_SYSTEM_MANAGER_EVENT_CREATE
)

func (x *CMsgParticleSystemManager) Reset() {
	*x = CMsgParticleSystemManager{}
	mi := &file_citadel_gameevents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager) ProtoMessage() {}

func (x *CMsgParticleSystemManager) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgParticleSystemManager) GetType() PARTICLE_SYSTEM_MANAGER_MESSAGE {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_CMsgParticleSystemManager_Type
}

func (x *CMsgParticleSystemManager) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *CMsgParticleSystemManager) GetCreateParticle() *CMsgParticleSystemManager_CreateParticle {
	if x != nil {
		return x.CreateParticle
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetDestroyParticle() *CMsgParticleSystemManager_DestroyParticle {
	if x != nil {
		return x.DestroyParticle
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetDestroyParticleInvolving() *CMsgParticleSystemManager_DestroyParticleInvolving {
	if x != nil {
		return x.DestroyParticleInvolving
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetReleaseParticleIndex() *CMsgParticleSystemManager_ReleaseParticleIndex {
	if x != nil {
		return x.ReleaseParticleIndex
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetUpdateParticle() *CMsgParticleSystemManager_UpdateParticle {
	if x != nil {
		return x.UpdateParticle
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetUpdateParticleFwd() *CMsgParticleSystemManager_UpdateParticleFwd {
	if x != nil {
		return x.UpdateParticleFwd
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetUpdateParticleOrient() *CMsgParticleSystemManager_UpdateParticleOrient {
	if x != nil {
		return x.UpdateParticleOrient
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetUpdateParticleFallback() *CMsgParticleSystemManager_UpdateParticleFallback {
	if x != nil {
		return x.UpdateParticleFallback
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetUpdateParticleOffset() *CMsgParticleSystemManager_UpdateParticleOffset {
	if x != nil {
		return x.UpdateParticleOffset
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetUpdateParticleEnt() *CMsgParticleSystemManager_UpdateParticleEnt {
	if x != nil {
		return x.UpdateParticleEnt
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetUpdateParticleFrozen() *CMsgParticleSystemManager_UpdateParticleFrozen {
	if x != nil {
		return x.UpdateParticleFrozen
	}
	return nil
}

func (x *CMsgParticleSystemManager) GetUpdateParticleShouldDraw() *CMsgParticleSystemManager_UpdateParticleShouldDraw {
	if x != nil {
		return x.UpdateParticleShouldDraw
	}
	return nil
}

type CMsgScreenTextPretty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XPos          *float32               `protobuf:"fixed32,1,opt,name=x_pos,json=xPos" json:"x_pos,omitempty"`
	YPos          *float32               `protobuf:"fixed32,2,opt,name=y_pos,json=yPos" json:"y_pos,omitempty"`
	Line          *int32                 `protobuf:"varint,3,opt,name=line" json:"line,omitempty"`
	Text          *string                `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	R             *int32                 `protobuf:"varint,5,opt,name=r" json:"r,omitempty"`
	G             *int32                 `protobuf:"varint,6,opt,name=g" json:"g,omitempty"`
	B             *int32                 `protobuf:"varint,7,opt,name=b" json:"b,omitempty"`
	A             *int32                 `protobuf:"varint,8,opt,name=a" json:"a,omitempty"`
	Duration      *float32               `protobuf:"fixed32,9,opt,name=duration" json:"duration,omitempty"`
	FontName      *string                `protobuf:"bytes,10,opt,name=font_name,json=fontName" json:"font_name,omitempty"`
	FontSize      *int32                 `protobuf:"varint,11,opt,name=font_size,json=fontSize" json:"font_size,omitempty"`
	BoldFont      *bool                  `protobuf:"varint,12,opt,name=bold_font,json=boldFont" json:"bold_font,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgScreenTextPretty) Reset() {
	*x = CMsgScreenTextPretty{}
	mi := &file_citadel_gameevents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgScreenTextPretty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgScreenTextPretty) ProtoMessage() {}

func (x *CMsgScreenTextPretty) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgScreenTextPretty.ProtoReflect.Descriptor instead.
func (*CMsgScreenTextPretty) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{4}
}

func (x *CMsgScreenTextPretty) GetXPos() float32 {
	if x != nil && x.XPos != nil {
		return *x.XPos
	}
	return 0
}

func (x *CMsgScreenTextPretty) GetYPos() float32 {
	if x != nil && x.YPos != nil {
		return *x.YPos
	}
	return 0
}

func (x *CMsgScreenTextPretty) GetLine() int32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *CMsgScreenTextPretty) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *CMsgScreenTextPretty) GetR() int32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

func (x *CMsgScreenTextPretty) GetG() int32 {
	if x != nil && x.G != nil {
		return *x.G
	}
	return 0
}

func (x *CMsgScreenTextPretty) GetB() int32 {
	if x != nil && x.B != nil {
		return *x.B
	}
	return 0
}

func (x *CMsgScreenTextPretty) GetA() int32 {
	if x != nil && x.A != nil {
		return *x.A
	}
	return 0
}

func (x *CMsgScreenTextPretty) GetDuration() float32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *CMsgScreenTextPretty) GetFontName() string {
	if x != nil && x.FontName != nil {
		return *x.FontName
	}
	return ""
}

func (x *CMsgScreenTextPretty) GetFontSize() int32 {
	if x != nil && x.FontSize != nil {
		return *x.FontSize
	}
	return 0
}

func (x *CMsgScreenTextPretty) GetBoldFont() bool {
	if x != nil && x.BoldFont != nil {
		return *x.BoldFont
	}
	return false
}

type CMsgServerRequestedTracer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        *CMsgVector            `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	End           *CMsgVector            `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
	Weaponid      *int32                 `protobuf:"varint,3,opt,name=weaponid,def=-1" json:"weaponid,omitempty"`
	EntityHandle  *uint32                `protobuf:"varint,4,opt,name=entity_handle,json=entityHandle,def=16777215" json:"entity_handle,omitempty"`
	Dps           *float32               `protobuf:"fixed32,5,opt,name=dps" json:"dps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgServerRequestedTracer fields.
const (
	Default_CMsgServerRequestedTracer_Weaponid     = int32(-1)
	Default_CMsgServerRequestedTracer_EntityHandle = uint32(16777215)
)

func (x *CMsgServerRequestedTracer) Reset() {
	*x = CMsgServerRequestedTracer{}
	mi := &file_citadel_gameevents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgServerRequestedTracer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgServerRequestedTracer) ProtoMessage() {}

func (x *CMsgServerRequestedTracer) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgServerRequestedTracer.ProtoReflect.Descriptor instead.
func (*CMsgServerRequestedTracer) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{5}
}

func (x *CMsgServerRequestedTracer) GetOrigin() *CMsgVector {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *CMsgServerRequestedTracer) GetEnd() *CMsgVector {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *CMsgServerRequestedTracer) GetWeaponid() int32 {
	if x != nil && x.Weaponid != nil {
		return *x.Weaponid
	}
	return Default_CMsgServerRequestedTracer_Weaponid
}

func (x *CMsgServerRequestedTracer) GetEntityHandle() uint32 {
	if x != nil && x.EntityHandle != nil {
		return *x.EntityHandle
	}
	return Default_CMsgServerRequestedTracer_EntityHandle
}

func (x *CMsgServerRequestedTracer) GetDps() float32 {
	if x != nil && x.Dps != nil {
		return *x.Dps
	}
	return 0
}

type CMsgEnableSatVolumesEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          *uint32                `protobuf:"varint,1,opt,name=mode" json:"mode,omitempty"`
	DesatAmount   *float32               `protobuf:"fixed32,2,opt,name=desat_amount,json=desatAmount" json:"desat_amount,omitempty"`
	SatTint       *uint32                `protobuf:"fixed32,3,opt,name=sat_tint,json=satTint" json:"sat_tint,omitempty"`
	DesatTint     *uint32                `protobuf:"fixed32,4,opt,name=desat_tint,json=desatTint" json:"desat_tint,omitempty"`
	OutlineColor  *uint32                `protobuf:"fixed32,5,opt,name=outline_color,json=outlineColor" json:"outline_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgEnableSatVolumesEvent) Reset() {
	*x = CMsgEnableSatVolumesEvent{}
	mi := &file_citadel_gameevents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgEnableSatVolumesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgEnableSatVolumesEvent) ProtoMessage() {}

func (x *CMsgEnableSatVolumesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgEnableSatVolumesEvent.ProtoReflect.Descriptor instead.
func (*CMsgEnableSatVolumesEvent) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{6}
}

func (x *CMsgEnableSatVolumesEvent) GetMode() uint32 {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return 0
}

func (x *CMsgEnableSatVolumesEvent) GetDesatAmount() float32 {
	if x != nil && x.DesatAmount != nil {
		return *x.DesatAmount
	}
	return 0
}

func (x *CMsgEnableSatVolumesEvent) GetSatTint() uint32 {
	if x != nil && x.SatTint != nil {
		return *x.SatTint
	}
	return 0
}

func (x *CMsgEnableSatVolumesEvent) GetDesatTint() uint32 {
	if x != nil && x.DesatTint != nil {
		return *x.DesatTint
	}
	return 0
}

func (x *CMsgEnableSatVolumesEvent) GetOutlineColor() uint32 {
	if x != nil && x.OutlineColor != nil {
		return *x.OutlineColor
	}
	return 0
}

type CMsgPlaceSatVolumeEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Position         *CMsgVector            `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	Direction        *CMsgVector            `protobuf:"bytes,2,opt,name=direction" json:"direction,omitempty"`
	Radius           *float32               `protobuf:"fixed32,3,opt,name=radius" json:"radius,omitempty"`
	FalloffDistance  *float32               `protobuf:"fixed32,4,opt,name=falloff_distance,json=falloffDistance" json:"falloff_distance,omitempty"`
	ThetaDot         *float32               `protobuf:"fixed32,5,opt,name=theta_dot,json=thetaDot" json:"theta_dot,omitempty"`
	PhiDot           *float32               `protobuf:"fixed32,6,opt,name=phi_dot,json=phiDot" json:"phi_dot,omitempty"`
	EntityHandle     *uint32                `protobuf:"varint,7,opt,name=entity_handle,json=entityHandle,def=16777215" json:"entity_handle,omitempty"`
	AttachmentHandle *uint32                `protobuf:"varint,8,opt,name=attachment_handle,json=attachmentHandle" json:"attachment_handle,omitempty"`
	Type             *uint32                `protobuf:"varint,9,opt,name=type" json:"type,omitempty"`
	VolumeId         *int32                 `protobuf:"varint,10,opt,name=volume_id,json=volumeId" json:"volume_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for CMsgPlaceSatVolumeEvent fields.
const (
	Default_CMsgPlaceSatVolumeEvent_EntityHandle = uint32(16777215)
)

func (x *CMsgPlaceSatVolumeEvent) Reset() {
	*x = CMsgPlaceSatVolumeEvent{}
	mi := &file_citadel_gameevents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgPlaceSatVolumeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgPlaceSatVolumeEvent) ProtoMessage() {}

func (x *CMsgPlaceSatVolumeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgPlaceSatVolumeEvent.ProtoReflect.Descriptor instead.
func (*CMsgPlaceSatVolumeEvent) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{7}
}

func (x *CMsgPlaceSatVolumeEvent) GetPosition() *CMsgVector {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CMsgPlaceSatVolumeEvent) GetDirection() *CMsgVector {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *CMsgPlaceSatVolumeEvent) GetRadius() float32 {
	if x != nil && x.Radius != nil {
		return *x.Radius
	}
	return 0
}

func (x *CMsgPlaceSatVolumeEvent) GetFalloffDistance() float32 {
	if x != nil && x.FalloffDistance != nil {
		return *x.FalloffDistance
	}
	return 0
}

func (x *CMsgPlaceSatVolumeEvent) GetThetaDot() float32 {
	if x != nil && x.ThetaDot != nil {
		return *x.ThetaDot
	}
	return 0
}

func (x *CMsgPlaceSatVolumeEvent) GetPhiDot() float32 {
	if x != nil && x.PhiDot != nil {
		return *x.PhiDot
	}
	return 0
}

func (x *CMsgPlaceSatVolumeEvent) GetEntityHandle() uint32 {
	if x != nil && x.EntityHandle != nil {
		return *x.EntityHandle
	}
	return Default_CMsgPlaceSatVolumeEvent_EntityHandle
}

func (x *CMsgPlaceSatVolumeEvent) GetAttachmentHandle() uint32 {
	if x != nil && x.AttachmentHandle != nil {
		return *x.AttachmentHandle
	}
	return 0
}

func (x *CMsgPlaceSatVolumeEvent) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *CMsgPlaceSatVolumeEvent) GetVolumeId() int32 {
	if x != nil && x.VolumeId != nil {
		return *x.VolumeId
	}
	return 0
}

type CMsgRemoveSatVolumeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      *int32                 `protobuf:"varint,1,opt,name=volume_id,json=volumeId" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgRemoveSatVolumeEvent) Reset() {
	*x = CMsgRemoveSatVolumeEvent{}
	mi := &file_citadel_gameevents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgRemoveSatVolumeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgRemoveSatVolumeEvent) ProtoMessage() {}

func (x *CMsgRemoveSatVolumeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgRemoveSatVolumeEvent.ProtoReflect.Descriptor instead.
func (*CMsgRemoveSatVolumeEvent) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{8}
}

func (x *CMsgRemoveSatVolumeEvent) GetVolumeId() int32 {
	if x != nil && x.VolumeId != nil {
		return *x.VolumeId
	}
	return 0
}

type CMsgDisableSatVolumesEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgDisableSatVolumesEvent) Reset() {
	*x = CMsgDisableSatVolumesEvent{}
	mi := &file_citadel_gameevents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgDisableSatVolumesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgDisableSatVolumesEvent) ProtoMessage() {}

func (x *CMsgDisableSatVolumesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgDisableSatVolumesEvent.ProtoReflect.Descriptor instead.
func (*CMsgDisableSatVolumesEvent) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{9}
}

type CMsgRemoveBullet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShooterEntindex *int32                 `protobuf:"varint,1,opt,name=shooter_entindex,json=shooterEntindex,def=-1" json:"shooter_entindex,omitempty"`
	ShotId          *uint32                `protobuf:"varint,2,opt,name=shot_id,json=shotId" json:"shot_id,omitempty"`
	BulletIndex     *uint32                `protobuf:"varint,3,opt,name=bullet_index,json=bulletIndex" json:"bullet_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for CMsgRemoveBullet fields.
const (
	Default_CMsgRemoveBullet_ShooterEntindex = int32(-1)
)

func (x *CMsgRemoveBullet) Reset() {
	*x = CMsgRemoveBullet{}
	mi := &file_citadel_gameevents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgRemoveBullet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgRemoveBullet) ProtoMessage() {}

func (x *CMsgRemoveBullet) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgRemoveBullet.ProtoReflect.Descriptor instead.
func (*CMsgRemoveBullet) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{10}
}

func (x *CMsgRemoveBullet) GetShooterEntindex() int32 {
	if x != nil && x.ShooterEntindex != nil {
		return *x.ShooterEntindex
	}
	return Default_CMsgRemoveBullet_ShooterEntindex
}

func (x *CMsgRemoveBullet) GetShotId() uint32 {
	if x != nil && x.ShotId != nil {
		return *x.ShotId
	}
	return 0
}

func (x *CMsgRemoveBullet) GetBulletIndex() uint32 {
	if x != nil && x.BulletIndex != nil {
		return *x.BulletIndex
	}
	return 0
}

type CMsgFireBullets_TracerAssignment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TracerResourceId *uint64                `protobuf:"varint,1,opt,name=tracer_resource_id,json=tracerResourceId" json:"tracer_resource_id,omitempty"`
	BulletIndicies   *uint32                `protobuf:"varint,2,opt,name=bullet_indicies,json=bulletIndicies" json:"bullet_indicies,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CMsgFireBullets_TracerAssignment) Reset() {
	*x = CMsgFireBullets_TracerAssignment{}
	mi := &file_citadel_gameevents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgFireBullets_TracerAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgFireBullets_TracerAssignment) ProtoMessage() {}

func (x *CMsgFireBullets_TracerAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgFireBullets_TracerAssignment.ProtoReflect.Descriptor instead.
func (*CMsgFireBullets_TracerAssignment) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CMsgFireBullets_TracerAssignment) GetTracerResourceId() uint64 {
	if x != nil && x.TracerResourceId != nil {
		return *x.TracerResourceId
	}
	return 0
}

func (x *CMsgFireBullets_TracerAssignment) GetBulletIndicies() uint32 {
	if x != nil && x.BulletIndicies != nil {
		return *x.BulletIndicies
	}
	return 0
}

type CMsgParticleSystemManager_CreateParticle struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ParticleNameIndex *uint64                `protobuf:"fixed64,1,opt,name=particle_name_index,json=particleNameIndex" json:"particle_name_index,omitempty"`
	AttachType        *int32                 `protobuf:"varint,2,opt,name=attach_type,json=attachType" json:"attach_type,omitempty"`
	EntityHandle      *uint32                `protobuf:"varint,3,opt,name=entity_handle,json=entityHandle,def=16777215" json:"entity_handle,omitempty"`
	Position          *CMsgVector            `protobuf:"bytes,4,opt,name=position" json:"position,omitempty"`
	Angles            *CMsgQAngle            `protobuf:"bytes,5,opt,name=angles" json:"angles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

// Default values for CMsgParticleSystemManager_CreateParticle fields.
const (
	Default_CMsgParticleSystemManager_CreateParticle_EntityHandle = uint32(16777215)
)

func (x *CMsgParticleSystemManager_CreateParticle) Reset() {
	*x = CMsgParticleSystemManager_CreateParticle{}
	mi := &file_citadel_gameevents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_CreateParticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_CreateParticle) ProtoMessage() {}

func (x *CMsgParticleSystemManager_CreateParticle) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_CreateParticle.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_CreateParticle) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CMsgParticleSystemManager_CreateParticle) GetParticleNameIndex() uint64 {
	if x != nil && x.ParticleNameIndex != nil {
		return *x.ParticleNameIndex
	}
	return 0
}

func (x *CMsgParticleSystemManager_CreateParticle) GetAttachType() int32 {
	if x != nil && x.AttachType != nil {
		return *x.AttachType
	}
	return 0
}

func (x *CMsgParticleSystemManager_CreateParticle) GetEntityHandle() uint32 {
	if x != nil && x.EntityHandle != nil {
		return *x.EntityHandle
	}
	return Default_CMsgParticleSystemManager_CreateParticle_EntityHandle
}

func (x *CMsgParticleSystemManager_CreateParticle) GetPosition() *CMsgVector {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CMsgParticleSystemManager_CreateParticle) GetAngles() *CMsgQAngle {
	if x != nil {
		return x.Angles
	}
	return nil
}

type CMsgParticleSystemManager_DestroyParticle struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DestroyImmediately *bool                  `protobuf:"varint,1,opt,name=destroy_immediately,json=destroyImmediately" json:"destroy_immediately,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CMsgParticleSystemManager_DestroyParticle) Reset() {
	*x = CMsgParticleSystemManager_DestroyParticle{}
	mi := &file_citadel_gameevents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_DestroyParticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_DestroyParticle) ProtoMessage() {}

func (x *CMsgParticleSystemManager_DestroyParticle) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_DestroyParticle.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_DestroyParticle) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 1}
}

func (x *CMsgParticleSystemManager_DestroyParticle) GetDestroyImmediately() bool {
	if x != nil && x.DestroyImmediately != nil {
		return *x.DestroyImmediately
	}
	return false
}

type CMsgParticleSystemManager_DestroyParticleInvolving struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DestroyImmediately *bool                  `protobuf:"varint,1,opt,name=destroy_immediately,json=destroyImmediately" json:"destroy_immediately,omitempty"`
	EntityHandle       *uint32                `protobuf:"varint,3,opt,name=entity_handle,json=entityHandle,def=16777215" json:"entity_handle,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for CMsgParticleSystemManager_DestroyParticleInvolving fields.
const (
	Default_CMsgParticleSystemManager_DestroyParticleInvolving_EntityHandle = uint32(16777215)
)

func (x *CMsgParticleSystemManager_DestroyParticleInvolving) Reset() {
	*x = CMsgParticleSystemManager_DestroyParticleInvolving{}
	mi := &file_citadel_gameevents_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_DestroyParticleInvolving) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_DestroyParticleInvolving) ProtoMessage() {}

func (x *CMsgParticleSystemManager_DestroyParticleInvolving) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_DestroyParticleInvolving.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_DestroyParticleInvolving) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 2}
}

func (x *CMsgParticleSystemManager_DestroyParticleInvolving) GetDestroyImmediately() bool {
	if x != nil && x.DestroyImmediately != nil {
		return *x.DestroyImmediately
	}
	return false
}

func (x *CMsgParticleSystemManager_DestroyParticleInvolving) GetEntityHandle() uint32 {
	if x != nil && x.EntityHandle != nil {
		return *x.EntityHandle
	}
	return Default_CMsgParticleSystemManager_DestroyParticleInvolving_EntityHandle
}

type CMsgParticleSystemManager_ReleaseParticleIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgParticleSystemManager_ReleaseParticleIndex) Reset() {
	*x = CMsgParticleSystemManager_ReleaseParticleIndex{}
	mi := &file_citadel_gameevents_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_ReleaseParticleIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_ReleaseParticleIndex) ProtoMessage() {}

func (x *CMsgParticleSystemManager_ReleaseParticleIndex) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_ReleaseParticleIndex.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_ReleaseParticleIndex) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 3}
}

type CMsgParticleSystemManager_UpdateParticle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlPoint  *int32                 `protobuf:"varint,1,opt,name=control_point,json=controlPoint" json:"control_point,omitempty"`
	Position      *CMsgVector            `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgParticleSystemManager_UpdateParticle) Reset() {
	*x = CMsgParticleSystemManager_UpdateParticle{}
	mi := &file_citadel_gameevents_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_UpdateParticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_UpdateParticle) ProtoMessage() {}

func (x *CMsgParticleSystemManager_UpdateParticle) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_UpdateParticle.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_UpdateParticle) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 4}
}

func (x *CMsgParticleSystemManager_UpdateParticle) GetControlPoint() int32 {
	if x != nil && x.ControlPoint != nil {
		return *x.ControlPoint
	}
	return 0
}

func (x *CMsgParticleSystemManager_UpdateParticle) GetPosition() *CMsgVector {
	if x != nil {
		return x.Position
	}
	return nil
}

type CMsgParticleSystemManager_UpdateParticleFwd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlPoint  *int32                 `protobuf:"varint,1,opt,name=control_point,json=controlPoint" json:"control_point,omitempty"`
	Forward       *CMsgVector            `protobuf:"bytes,2,opt,name=forward" json:"forward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgParticleSystemManager_UpdateParticleFwd) Reset() {
	*x = CMsgParticleSystemManager_UpdateParticleFwd{}
	mi := &file_citadel_gameevents_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_UpdateParticleFwd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_UpdateParticleFwd) ProtoMessage() {}

func (x *CMsgParticleSystemManager_UpdateParticleFwd) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_UpdateParticleFwd.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_UpdateParticleFwd) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 5}
}

func (x *CMsgParticleSystemManager_UpdateParticleFwd) GetControlPoint() int32 {
	if x != nil && x.ControlPoint != nil {
		return *x.ControlPoint
	}
	return 0
}

func (x *CMsgParticleSystemManager_UpdateParticleFwd) GetForward() *CMsgVector {
	if x != nil {
		return x.Forward
	}
	return nil
}

type CMsgParticleSystemManager_UpdateParticleOrient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlPoint  *int32                 `protobuf:"varint,1,opt,name=control_point,json=controlPoint" json:"control_point,omitempty"`
	Forward       *CMsgVector            `protobuf:"bytes,2,opt,name=forward" json:"forward,omitempty"`
	Left          *CMsgVector            `protobuf:"bytes,3,opt,name=left" json:"left,omitempty"`
	Up            *CMsgVector            `protobuf:"bytes,4,opt,name=up" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgParticleSystemManager_UpdateParticleOrient) Reset() {
	*x = CMsgParticleSystemManager_UpdateParticleOrient{}
	mi := &file_citadel_gameevents_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_UpdateParticleOrient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_UpdateParticleOrient) ProtoMessage() {}

func (x *CMsgParticleSystemManager_UpdateParticleOrient) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_UpdateParticleOrient.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_UpdateParticleOrient) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 6}
}

func (x *CMsgParticleSystemManager_UpdateParticleOrient) GetControlPoint() int32 {
	if x != nil && x.ControlPoint != nil {
		return *x.ControlPoint
	}
	return 0
}

func (x *CMsgParticleSystemManager_UpdateParticleOrient) GetForward() *CMsgVector {
	if x != nil {
		return x.Forward
	}
	return nil
}

func (x *CMsgParticleSystemManager_UpdateParticleOrient) GetLeft() *CMsgVector {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *CMsgParticleSystemManager_UpdateParticleOrient) GetUp() *CMsgVector {
	if x != nil {
		return x.Up
	}
	return nil
}

type CMsgParticleSystemManager_UpdateParticleFallback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlPoint  *int32                 `protobuf:"varint,1,opt,name=control_point,json=controlPoint" json:"control_point,omitempty"`
	Position      *CMsgVector            `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgParticleSystemManager_UpdateParticleFallback) Reset() {
	*x = CMsgParticleSystemManager_UpdateParticleFallback{}
	mi := &file_citadel_gameevents_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_UpdateParticleFallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_UpdateParticleFallback) ProtoMessage() {}

func (x *CMsgParticleSystemManager_UpdateParticleFallback) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_UpdateParticleFallback.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_UpdateParticleFallback) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 7}
}

func (x *CMsgParticleSystemManager_UpdateParticleFallback) GetControlPoint() int32 {
	if x != nil && x.ControlPoint != nil {
		return *x.ControlPoint
	}
	return 0
}

func (x *CMsgParticleSystemManager_UpdateParticleFallback) GetPosition() *CMsgVector {
	if x != nil {
		return x.Position
	}
	return nil
}

type CMsgParticleSystemManager_UpdateParticleEnt struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ControlPoint     *int32                 `protobuf:"varint,1,opt,name=control_point,json=controlPoint" json:"control_point,omitempty"`
	EntityHandle     *uint32                `protobuf:"varint,2,opt,name=entity_handle,json=entityHandle,def=16777215" json:"entity_handle,omitempty"`
	AttachType       *int32                 `protobuf:"varint,3,opt,name=attach_type,json=attachType" json:"attach_type,omitempty"`
	Attachment       *int32                 `protobuf:"varint,4,opt,name=attachment" json:"attachment,omitempty"`
	FallbackPosition *CMsgVector            `protobuf:"bytes,5,opt,name=fallback_position,json=fallbackPosition" json:"fallback_position,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for CMsgParticleSystemManager_UpdateParticleEnt fields.
const (
	Default_CMsgParticleSystemManager_UpdateParticleEnt_EntityHandle = uint32(16777215)
)

func (x *CMsgParticleSystemManager_UpdateParticleEnt) Reset() {
	*x = CMsgParticleSystemManager_UpdateParticleEnt{}
	mi := &file_citadel_gameevents_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_UpdateParticleEnt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_UpdateParticleEnt) ProtoMessage() {}

func (x *CMsgParticleSystemManager_UpdateParticleEnt) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_UpdateParticleEnt.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_UpdateParticleEnt) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 8}
}

func (x *CMsgParticleSystemManager_UpdateParticleEnt) GetControlPoint() int32 {
	if x != nil && x.ControlPoint != nil {
		return *x.ControlPoint
	}
	return 0
}

func (x *CMsgParticleSystemManager_UpdateParticleEnt) GetEntityHandle() uint32 {
	if x != nil && x.EntityHandle != nil {
		return *x.EntityHandle
	}
	return Default_CMsgParticleSystemManager_UpdateParticleEnt_EntityHandle
}

func (x *CMsgParticleSystemManager_UpdateParticleEnt) GetAttachType() int32 {
	if x != nil && x.AttachType != nil {
		return *x.AttachType
	}
	return 0
}

func (x *CMsgParticleSystemManager_UpdateParticleEnt) GetAttachment() int32 {
	if x != nil && x.Attachment != nil {
		return *x.Attachment
	}
	return 0
}

func (x *CMsgParticleSystemManager_UpdateParticleEnt) GetFallbackPosition() *CMsgVector {
	if x != nil {
		return x.FallbackPosition
	}
	return nil
}

type CMsgParticleSystemManager_UpdateParticleOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlPoint  *int32                 `protobuf:"varint,1,opt,name=control_point,json=controlPoint" json:"control_point,omitempty"`
	OriginOffset  *CMsgVector            `protobuf:"bytes,2,opt,name=origin_offset,json=originOffset" json:"origin_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgParticleSystemManager_UpdateParticleOffset) Reset() {
	*x = CMsgParticleSystemManager_UpdateParticleOffset{}
	mi := &file_citadel_gameevents_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_UpdateParticleOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_UpdateParticleOffset) ProtoMessage() {}

func (x *CMsgParticleSystemManager_UpdateParticleOffset) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_UpdateParticleOffset.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_UpdateParticleOffset) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 9}
}

func (x *CMsgParticleSystemManager_UpdateParticleOffset) GetControlPoint() int32 {
	if x != nil && x.ControlPoint != nil {
		return *x.ControlPoint
	}
	return 0
}

func (x *CMsgParticleSystemManager_UpdateParticleOffset) GetOriginOffset() *CMsgVector {
	if x != nil {
		return x.OriginOffset
	}
	return nil
}

type CMsgParticleSystemManager_UpdateParticleFrozen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetFrozen     *bool                  `protobuf:"varint,1,opt,name=set_frozen,json=setFrozen" json:"set_frozen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgParticleSystemManager_UpdateParticleFrozen) Reset() {
	*x = CMsgParticleSystemManager_UpdateParticleFrozen{}
	mi := &file_citadel_gameevents_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_UpdateParticleFrozen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_UpdateParticleFrozen) ProtoMessage() {}

func (x *CMsgParticleSystemManager_UpdateParticleFrozen) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_UpdateParticleFrozen.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_UpdateParticleFrozen) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 10}
}

func (x *CMsgParticleSystemManager_UpdateParticleFrozen) GetSetFrozen() bool {
	if x != nil && x.SetFrozen != nil {
		return *x.SetFrozen
	}
	return false
}

type CMsgParticleSystemManager_UpdateParticleShouldDraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShouldDraw    *bool                  `protobuf:"varint,1,opt,name=should_draw,json=shouldDraw" json:"should_draw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgParticleSystemManager_UpdateParticleShouldDraw) Reset() {
	*x = CMsgParticleSystemManager_UpdateParticleShouldDraw{}
	mi := &file_citadel_gameevents_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgParticleSystemManager_UpdateParticleShouldDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgParticleSystemManager_UpdateParticleShouldDraw) ProtoMessage() {}

func (x *CMsgParticleSystemManager_UpdateParticleShouldDraw) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gameevents_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgParticleSystemManager_UpdateParticleShouldDraw.ProtoReflect.Descriptor instead.
func (*CMsgParticleSystemManager_UpdateParticleShouldDraw) Descriptor() ([]byte, []int) {
	return file_citadel_gameevents_proto_rawDescGZIP(), []int{3, 11}
}

func (x *CMsgParticleSystemManager_UpdateParticleShouldDraw) GetShouldDraw() bool {
	if x != nil && x.ShouldDraw != nil {
		return *x.ShouldDraw
	}
	return false
}

var File_citadel_gameevents_proto protoreflect.FileDescriptor

const file_citadel_gameevents_proto_rawDesc = "" +
	"\n" +
	"\x18citadel_gameevents.proto\x12\bdeadlock\x1a google/protobuf/descriptor.proto\x1a\x16networkbasetypes.proto\"\x89\t\n" +
	"\x0fCMsgFireBullets\x12,\n" +
	"\x06origin\x18\x01 \x01(\v2\x14.deadlock.CMsgVectorR\x06origin\x12,\n" +
	"\x06angles\x18\x02 \x01(\v2\x14.deadlock.CMsgQAngleR\x06angles\x12\x12\n" +
	"\x04seed\x18\x04 \x01(\rR\x04seed\x12)\n" +
	"\x0eshooter_entity\x18\x05 \x01(\x05:\x02-1R\rshooterEntity\x12\x1c\n" +
	"\aability\x18\a \x01(\x05:\x02-1R\aability\x12/\n" +
	"\x13penetration_percent\x18\b \x01(\x02R\x12penetrationPercent\x12\x16\n" +
	"\x06spread\x18\t \x01(\x02R\x06spread\x12*\n" +
	"\x0efired_from_gun\x18\n" +
	" \x01(\b:\x04trueR\ffiredFromGun\x12)\n" +
	"\x10bullets_override\x18\v \x01(\rR\x0fbulletsOverride\x12Y\n" +
	"\x12tracer_replacement\x18\f \x01(\v2*.deadlock.CMsgFireBullets.TracerAssignmentR\x11tracerReplacement\x12W\n" +
	"\x11tracer_additional\x18\r \x03(\v2*.deadlock.CMsgFireBullets.TracerAssignmentR\x10tracerAdditional\x12=\n" +
	"\x0fangles_original\x18\x0e \x01(\v2\x14.deadlock.CMsgQAngleR\x0eanglesOriginal\x12,\n" +
	"\x12weapon_subclass_id\x18\x0f \x01(\rR\x10weaponSubclassId\x12\x1f\n" +
	"\vshot_number\x18\x10 \x01(\rR\n" +
	"shotNumber\x12'\n" +
	"\rignore_entity\x18\x11 \x01(\x05:\x02-1R\fignoreEntity\x12\x1b\n" +
	"\tmax_range\x18\x12 \x01(\x02R\bmaxRange\x12\x17\n" +
	"\ashot_id\x18\x13 \x01(\rR\x06shotId\x12A\n" +
	"\x1apredict_hits_against_units\x18\x14 \x01(\b:\x04trueR\x17predictHitsAgainstUnits\x127\n" +
	"\x16bullet_radius_override\x18\x15 \x01(\x02:\x010R\x14bulletRadiusOverride\x125\n" +
	"\x15bullet_speed_override\x18\x16 \x01(\x02:\x010R\x13bulletSpeedOverride\x129\n" +
	"\x17bullet_gravity_override\x18\x17 \x01(\x02:\x010R\x15bulletGravityOverride\x12#\n" +
	"\rmuzzle_number\x18\x18 \x01(\x05R\fmuzzleNumber\x1ai\n" +
	"\x10TracerAssignment\x12,\n" +
	"\x12tracer_resource_id\x18\x01 \x01(\x04R\x10tracerResourceId\x12'\n" +
	"\x0fbullet_indicies\x18\x02 \x01(\rR\x0ebulletIndicies\"\xf5\x03\n" +
	"\x10CMsgBulletImpact\x125\n" +
	"\vtrace_start\x18\x01 \x01(\v2\x14.deadlock.CMsgVectorR\n" +
	"traceStart\x129\n" +
	"\rimpact_origin\x18\x02 \x01(\v2\x14.deadlock.CMsgVectorR\fimpactOrigin\x12;\n" +
	"\x0esurface_normal\x18\x03 \x01(\v2\x14.deadlock.CMsgVectorR\rsurfaceNormal\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\rR\x06damage\x12!\n" +
	"\fsurface_type\x18\x05 \x01(\rR\vsurfaceType\x121\n" +
	"\x0fability_ehandle\x18\a \x01(\r:\b16777215R\x0eabilityEhandle\x123\n" +
	"\x10impacted_ehandle\x18\b \x01(\r:\b16777215R\x0fimpactedEhandle\x12.\n" +
	"\x13impacted_bone_index\x18\t \x01(\rR\x11impactedBoneIndex\x12,\n" +
	"\x12weapon_subclass_id\x18\n" +
	" \x01(\rR\x10weaponSubclassId\x121\n" +
	"\x0fshooter_ehandle\x18\v \x01(\r:\b16777215R\x0eshooterEhandle\"a\n" +
	"\x13CMsgPlayerAnimEvent\x12 \n" +
	"\x06player\x18\x01 \x01(\a:\b16777215R\x06player\x12\x14\n" +
	"\x05event\x18\x02 \x01(\rR\x05event\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x05R\x04data\"\xd4\x16\n" +
	"\x19CMsgParticleSystemManager\x12c\n" +
	"\x04type\x18\x01 \x02(\x0e2).deadlock.PARTICLE_SYSTEM_MANAGER_MESSAGE:$PARTICLE_SYSTEM_MANAGER_EVENT_CREATER\x04type\x12\x14\n" +
	"\x05index\x18\x02 \x02(\rR\x05index\x12[\n" +
	"\x0fcreate_particle\x18\x03 \x01(\v22.deadlock.CMsgParticleSystemManager.CreateParticleR\x0ecreateParticle\x12^\n" +
	"\x10destroy_particle\x18\x04 \x01(\v23.deadlock.CMsgParticleSystemManager.DestroyParticleR\x0fdestroyParticle\x12z\n" +
	"\x1adestroy_particle_involving\x18\x05 \x01(\v2<.deadlock.CMsgParticleSystemManager.DestroyParticleInvolvingR\x18destroyParticleInvolving\x12n\n" +
	"\x16release_particle_index\x18\x06 \x01(\v28.deadlock.CMsgParticleSystemManager.ReleaseParticleIndexR\x14releaseParticleIndex\x12[\n" +
	"\x0fupdate_particle\x18\a \x01(\v22.deadlock.CMsgParticleSystemManager.UpdateParticleR\x0eupdateParticle\x12e\n" +
	"\x13update_particle_fwd\x18\b \x01(\v25.deadlock.CMsgParticleSystemManager.UpdateParticleFwdR\x11updateParticleFwd\x12n\n" +
	"\x16update_particle_orient\x18\t \x01(\v28.deadlock.CMsgParticleSystemManager.UpdateParticleOrientR\x14updateParticleOrient\x12t\n" +
	"\x18update_particle_fallback\x18\n" +
	" \x01(\v2:.deadlock.CMsgParticleSystemManager.UpdateParticleFallbackR\x16updateParticleFallback\x12n\n" +
	"\x16update_particle_offset\x18\v \x01(\v28.deadlock.CMsgParticleSystemManager.UpdateParticleOffsetR\x14updateParticleOffset\x12e\n" +
	"\x13update_particle_ent\x18\f \x01(\v25.deadlock.CMsgParticleSystemManager.UpdateParticleEntR\x11updateParticleEnt\x12n\n" +
	"\x16update_particle_frozen\x18\r \x01(\v28.deadlock.CMsgParticleSystemManager.UpdateParticleFrozenR\x14updateParticleFrozen\x12{\n" +
	"\x1bupdate_particle_should_draw\x18\x0e \x01(\v2<.deadlock.CMsgParticleSystemManager.UpdateParticleShouldDrawR\x18updateParticleShouldDraw\x1a\xf0\x01\n" +
	"\x0eCreateParticle\x12.\n" +
	"\x13particle_name_index\x18\x01 \x01(\x06R\x11particleNameIndex\x12\x1f\n" +
	"\vattach_type\x18\x02 \x01(\x05R\n" +
	"attachType\x12-\n" +
	"\rentity_handle\x18\x03 \x01(\r:\b16777215R\fentityHandle\x120\n" +
	"\bposition\x18\x04 \x01(\v2\x14.deadlock.CMsgVectorR\bposition\x12,\n" +
	"\x06angles\x18\x05 \x01(\v2\x14.deadlock.CMsgQAngleR\x06angles\x1aB\n" +
	"\x0fDestroyParticle\x12/\n" +
	"\x13destroy_immediately\x18\x01 \x01(\bR\x12destroyImmediately\x1az\n" +
	"\x18DestroyParticleInvolving\x12/\n" +
	"\x13destroy_immediately\x18\x01 \x01(\bR\x12destroyImmediately\x12-\n" +
	"\rentity_handle\x18\x03 \x01(\r:\b16777215R\fentityHandle\x1a\x16\n" +
	"\x14ReleaseParticleIndex\x1ag\n" +
	"\x0eUpdateParticle\x12#\n" +
	"\rcontrol_point\x18\x01 \x01(\x05R\fcontrolPoint\x120\n" +
	"\bposition\x18\x02 \x01(\v2\x14.deadlock.CMsgVectorR\bposition\x1ah\n" +
	"\x11UpdateParticleFwd\x12#\n" +
	"\rcontrol_point\x18\x01 \x01(\x05R\fcontrolPoint\x12.\n" +
	"\aforward\x18\x02 \x01(\v2\x14.deadlock.CMsgVectorR\aforward\x1a\xbb\x01\n" +
	"\x14UpdateParticleOrient\x12#\n" +
	"\rcontrol_point\x18\x01 \x01(\x05R\fcontrolPoint\x12.\n" +
	"\aforward\x18\x02 \x01(\v2\x14.deadlock.CMsgVectorR\aforward\x12(\n" +
	"\x04left\x18\x03 \x01(\v2\x14.deadlock.CMsgVectorR\x04left\x12$\n" +
	"\x02up\x18\x04 \x01(\v2\x14.deadlock.CMsgVectorR\x02up\x1ao\n" +
	"\x16UpdateParticleFallback\x12#\n" +
	"\rcontrol_point\x18\x01 \x01(\x05R\fcontrolPoint\x120\n" +
	"\bposition\x18\x02 \x01(\v2\x14.deadlock.CMsgVectorR\bposition\x1a\xeb\x01\n" +
	"\x11UpdateParticleEnt\x12#\n" +
	"\rcontrol_point\x18\x01 \x01(\x05R\fcontrolPoint\x12-\n" +
	"\rentity_handle\x18\x02 \x01(\r:\b16777215R\fentityHandle\x12\x1f\n" +
	"\vattach_type\x18\x03 \x01(\x05R\n" +
	"attachType\x12\x1e\n" +
	"\n" +
	"attachment\x18\x04 \x01(\x05R\n" +
	"attachment\x12A\n" +
	"\x11fallback_position\x18\x05 \x01(\v2\x14.deadlock.CMsgVectorR\x10fallbackPosition\x1av\n" +
	"\x14UpdateParticleOffset\x12#\n" +
	"\rcontrol_point\x18\x01 \x01(\x05R\fcontrolPoint\x129\n" +
	"\rorigin_offset\x18\x02 \x01(\v2\x14.deadlock.CMsgVectorR\foriginOffset\x1a5\n" +
	"\x14UpdateParticleFrozen\x12\x1d\n" +
	"\n" +
	"set_frozen\x18\x01 \x01(\bR\tsetFrozen\x1a;\n" +
	"\x18UpdateParticleShouldDraw\x12\x1f\n" +
	"\vshould_draw\x18\x01 \x01(\bR\n" +
	"shouldDraw\"\x93\x02\n" +
	"\x14CMsgScreenTextPretty\x12\x13\n" +
	"\x05x_pos\x18\x01 \x01(\x02R\x04xPos\x12\x13\n" +
	"\x05y_pos\x18\x02 \x01(\x02R\x04yPos\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\f\n" +
	"\x01r\x18\x05 \x01(\x05R\x01r\x12\f\n" +
	"\x01g\x18\x06 \x01(\x05R\x01g\x12\f\n" +
	"\x01b\x18\a \x01(\x05R\x01b\x12\f\n" +
	"\x01a\x18\b \x01(\x05R\x01a\x12\x1a\n" +
	"\bduration\x18\t \x01(\x02R\bduration\x12\x1b\n" +
	"\tfont_name\x18\n" +
	" \x01(\tR\bfontName\x12\x1b\n" +
	"\tfont_size\x18\v \x01(\x05R\bfontSize\x12\x1b\n" +
	"\tbold_font\x18\f \x01(\bR\bboldFont\"\xd2\x01\n" +
	"\x19CMsgServerRequestedTracer\x12,\n" +
	"\x06origin\x18\x01 \x01(\v2\x14.deadlock.CMsgVectorR\x06origin\x12&\n" +
	"\x03end\x18\x02 \x01(\v2\x14.deadlock.CMsgVectorR\x03end\x12\x1e\n" +
	"\bweaponid\x18\x03 \x01(\x05:\x02-1R\bweaponid\x12-\n" +
	"\rentity_handle\x18\x04 \x01(\r:\b16777215R\fentityHandle\x12\x10\n" +
	"\x03dps\x18\x05 \x01(\x02R\x03dps\"\xb1\x01\n" +
	"\x19CMsgEnableSatVolumesEvent\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\rR\x04mode\x12!\n" +
	"\fdesat_amount\x18\x02 \x01(\x02R\vdesatAmount\x12\x19\n" +
	"\bsat_tint\x18\x03 \x01(\aR\asatTint\x12\x1d\n" +
	"\n" +
	"desat_tint\x18\x04 \x01(\aR\tdesatTint\x12#\n" +
	"\routline_color\x18\x05 \x01(\aR\foutlineColor\"\x85\x03\n" +
	"\x17CMsgPlaceSatVolumeEvent\x120\n" +
	"\bposition\x18\x01 \x01(\v2\x14.deadlock.CMsgVectorR\bposition\x122\n" +
	"\tdirection\x18\x02 \x01(\v2\x14.deadlock.CMsgVectorR\tdirection\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x02R\x06radius\x12)\n" +
	"\x10falloff_distance\x18\x04 \x01(\x02R\x0ffalloffDistance\x12\x1b\n" +
	"\ttheta_dot\x18\x05 \x01(\x02R\bthetaDot\x12\x17\n" +
	"\aphi_dot\x18\x06 \x01(\x02R\x06phiDot\x12-\n" +
	"\rentity_handle\x18\a \x01(\r:\b16777215R\fentityHandle\x12+\n" +
	"\x11attachment_handle\x18\b \x01(\rR\x10attachmentHandle\x12\x12\n" +
	"\x04type\x18\t \x01(\rR\x04type\x12\x1b\n" +
	"\tvolume_id\x18\n" +
	" \x01(\x05R\bvolumeId\"7\n" +
	"\x18CMsgRemoveSatVolumeEvent\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\x05R\bvolumeId\"\x1c\n" +
	"\x1aCMsgDisableSatVolumesEvent\"}\n" +
	"\x10CMsgRemoveBullet\x12-\n" +
	"\x10shooter_entindex\x18\x01 \x01(\x05:\x02-1R\x0fshooterEntindex\x12\x17\n" +
	"\ashot_id\x18\x02 \x01(\rR\x06shotId\x12!\n" +
	"\fbullet_index\x18\x03 \x01(\rR\vbulletIndex*\xa1\x02\n" +
	"\x12ECitadelGameEvents\x12\x13\n" +
	"\x0eGE_FireBullets\x10\xc2\x03\x12\x17\n" +
	"\x12GE_PlayerAnimEvent\x10\xc3\x03\x12\x1d\n" +
	"\x18GE_ParticleSystemManager\x10\xca\x03\x12\x18\n" +
	"\x13GE_ScreenTextPretty\x10\xcb\x03\x12\x14\n" +
	"\x0fGE_BulletImpact\x10\xcd\x03\x12\x1d\n" +
	"\x18GE_EnableSatVolumesEvent\x10\xce\x03\x12\x1b\n" +
	"\x16GE_PlaceSatVolumeEvent\x10\xcf\x03\x12\x1e\n" +
	"\x19GE_DisableSatVolumesEvent\x10\xd0\x03\x12\x1c\n" +
	"\x17GE_RemoveSatVolumeEvent\x10\xd1\x03\x12\x14\n" +
	"\x0fGE_RemoveBullet\x10\xd2\x03*\xe1\x04\n" +
	"\x1fPARTICLE_SYSTEM_MANAGER_MESSAGE\x12(\n" +
	"$PARTICLE_SYSTEM_MANAGER_EVENT_CREATE\x10\x00\x12)\n" +
	"%PARTICLE_SYSTEM_MANAGER_EVENT_DESTROY\x10\x01\x123\n" +
	"/PARTICLE_SYSTEM_MANAGER_EVENT_DESTROY_INVOLVING\x10\x02\x12)\n" +
	"%PARTICLE_SYSTEM_MANAGER_EVENT_RELEASE\x10\x03\x12(\n" +
	"$PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE\x10\x04\x120\n" +
	",PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FORWARD\x10\x05\x124\n" +
	"0PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_ORIENTATION\x10\x06\x121\n" +
	"-PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FALLBACK\x10\a\x12,\n" +
	"(PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_ENT\x10\b\x12/\n" +
	"+PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_OFFSET\x10\t\x12/\n" +
	"+PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_FROZEN\x10\n" +
	"\x124\n" +
	"0PARTICLE_SYSTEM_MANAGER_EVENT_UPDATE_SHOULD_DRAW\x10\vB4Z2github.com/RyPort/paradox-parser/deadlock;deadlock"

var (
	file_citadel_gameevents_proto_rawDescOnce sync.Once
	file_citadel_gameevents_proto_rawDescData []byte
)

func file_citadel_gameevents_proto_rawDescGZIP() []byte {
	file_citadel_gameevents_proto_rawDescOnce.Do(func() {
		file_citadel_gameevents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_citadel_gameevents_proto_rawDesc), len(file_citadel_gameevents_proto_rawDesc)))
	})
	return file_citadel_gameevents_proto_rawDescData
}

var file_citadel_gameevents_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_citadel_gameevents_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_citadel_gameevents_proto_goTypes = []any{
	(ECitadelGameEvents)(0),                                    // 0: deadlock.ECitadelGameEvents
	(PARTICLE_SYSTEM_MANAGER_MESSAGE)(0),                       // 1: deadlock.PARTICLE_SYSTEM_MANAGER_MESSAGE
	(*CMsgFireBullets)(nil),                                    // 2: deadlock.CMsgFireBullets
	(*CMsgBulletImpact)(nil),                                   // 3: deadlock.CMsgBulletImpact
	(*CMsgPlayerAnimEvent)(nil),                                // 4: deadlock.CMsgPlayerAnimEvent
	(*CMsgParticleSystemManager)(nil),                          // 5: deadlock.CMsgParticleSystemManager
	(*CMsgScreenTextPretty)(nil),                               // 6: deadlock.CMsgScreenTextPretty
	(*CMsgServerRequestedTracer)(nil),                          // 7: deadlock.CMsgServerRequestedTracer
	(*CMsgEnableSatVolumesEvent)(nil),                          // 8: deadlock.CMsgEnableSatVolumesEvent
	(*CMsgPlaceSatVolumeEvent)(nil),                            // 9: deadlock.CMsgPlaceSatVolumeEvent
	(*CMsgRemoveSatVolumeEvent)(nil),                           // 10: deadlock.CMsgRemoveSatVolumeEvent
	(*CMsgDisableSatVolumesEvent)(nil),                         // 11: deadlock.CMsgDisableSatVolumesEvent
	(*CMsgRemoveBullet)(nil),                                   // 12: deadlock.CMsgRemoveBullet
	(*CMsgFireBullets_TracerAssignment)(nil),                   // 13: deadlock.CMsgFireBullets.TracerAssignment
	(*CMsgParticleSystemManager_CreateParticle)(nil),           // 14: deadlock.CMsgParticleSystemManager.CreateParticle
	(*CMsgParticleSystemManager_DestroyParticle)(nil),          // 15: deadlock.CMsgParticleSystemManager.DestroyParticle
	(*CMsgParticleSystemManager_DestroyParticleInvolving)(nil), // 16: deadlock.CMsgParticleSystemManager.DestroyParticleInvolving
	(*CMsgParticleSystemManager_ReleaseParticleIndex)(nil),     // 17: deadlock.CMsgParticleSystemManager.ReleaseParticleIndex
	(*CMsgParticleSystemManager_UpdateParticle)(nil),           // 18: deadlock.CMsgParticleSystemManager.UpdateParticle
	(*CMsgParticleSystemManager_UpdateParticleFwd)(nil),        // 19: deadlock.CMsgParticleSystemManager.UpdateParticleFwd
	(*CMsgParticleSystemManager_UpdateParticleOrient)(nil),     // 20: deadlock.CMsgParticleSystemManager.UpdateParticleOrient
	(*CMsgParticleSystemManager_UpdateParticleFallback)(nil),   // 21: deadlock.CMsgParticleSystemManager.UpdateParticleFallback
	(*CMsgParticleSystemManager_UpdateParticleEnt)(nil),        // 22: deadlock.CMsgParticleSystemManager.UpdateParticleEnt
	(*CMsgParticleSystemManager_UpdateParticleOffset)(nil),     // 23: deadlock.CMsgParticleSystemManager.UpdateParticleOffset
	(*CMsgParticleSystemManager_UpdateParticleFrozen)(nil),     // 24: deadlock.CMsgParticleSystemManager.UpdateParticleFrozen
	(*CMsgParticleSystemManager_UpdateParticleShouldDraw)(nil), // 25: deadlock.CMsgParticleSystemManager.UpdateParticleShouldDraw
	(*CMsgVector)(nil),                                         // 26: deadlock.CMsgVector
	(*CMsgQAngle)(nil),                                         // 27: deadlock.CMsgQAngle
}
var file_citadel_gameevents_proto_depIdxs = []int32{
	26, // 0: deadlock.CMsgFireBullets.origin:type_name -> deadlock.CMsgVector
	27, // 1: deadlock.CMsgFireBullets.angles:type_name -> deadlock.CMsgQAngle
	13, // 2: deadlock.CMsgFireBullets.tracer_replacement:type_name -> deadlock.CMsgFireBullets.TracerAssignment
	13, // 3: deadlock.CMsgFireBullets.tracer_additional:type_name -> deadlock.CMsgFireBullets.TracerAssignment
	27, // 4: deadlock.CMsgFireBullets.angles_original:type_name -> deadlock.CMsgQAngle
	26, // 5: deadlock.CMsgBulletImpact.trace_start:type_name -> deadlock.CMsgVector
	26, // 6: deadlock.CMsgBulletImpact.impact_origin:type_name -> deadlock.CMsgVector
	26, // 7: deadlock.CMsgBulletImpact.surface_normal:type_name -> deadlock.CMsgVector
	1,  // 8: deadlock.CMsgParticleSystemManager.type:type_name -> deadlock.PARTICLE_SYSTEM_MANAGER_MESSAGE
	14, // 9: deadlock.CMsgParticleSystemManager.create_particle:type_name -> deadlock.CMsgParticleSystemManager.CreateParticle
	15, // 10: deadlock.CMsgParticleSystemManager.destroy_particle:type_name -> deadlock.CMsgParticleSystemManager.DestroyParticle
	16, // 11: deadlock.CMsgParticleSystemManager.destroy_particle_involving:type_name -> deadlock.CMsgParticleSystemManager.DestroyParticleInvolving
	17, // 12: deadlock.CMsgParticleSystemManager.release_particle_index:type_name -> deadlock.CMsgParticleSystemManager.ReleaseParticleIndex
	18, // 13: deadlock.CMsgParticleSystemManager.update_particle:type_name -> deadlock.CMsgParticleSystemManager.UpdateParticle
	19, // 14: deadlock.CMsgParticleSystemManager.update_particle_fwd:type_name -> deadlock.CMsgParticleSystemManager.UpdateParticleFwd
	20, // 15: deadlock.CMsgParticleSystemManager.update_particle_orient:type_name -> deadlock.CMsgParticleSystemManager.UpdateParticleOrient
	21, // 16: deadlock.CMsgParticleSystemManager.update_particle_fallback:type_name -> deadlock.CMsgParticleSystemManager.UpdateParticleFallback
	23, // 17: deadlock.CMsgParticleSystemManager.update_particle_offset:type_name -> deadlock.CMsgParticleSystemManager.UpdateParticleOffset
	22, // 18: deadlock.CMsgParticleSystemManager.update_particle_ent:type_name -> deadlock.CMsgParticleSystemManager.UpdateParticleEnt
	24, // 19: deadlock.CMsgParticleSystemManager.update_particle_frozen:type_name -> deadlock.CMsgParticleSystemManager.UpdateParticleFrozen
	25, // 20: deadlock.CMsgParticleSystemManager.update_particle_should_draw:type_name -> deadlock.CMsgParticleSystemManager.UpdateParticleShouldDraw
	26, // 21: deadlock.CMsgServerRequestedTracer.origin:type_name -> deadlock.CMsgVector
	26, // 22: deadlock.CMsgServerRequestedTracer.end:type_name -> deadlock.CMsgVector
	26, // 23: deadlock.CMsgPlaceSatVolumeEvent.position:type_name -> deadlock.CMsgVector
	26, // 24: deadlock.CMsgPlaceSatVolumeEvent.direction:type_name -> deadlock.CMsgVector
	26, // 25: deadlock.CMsgParticleSystemManager.CreateParticle.position:type_name -> deadlock.CMsgVector
	27, // 26: deadlock.CMsgParticleSystemManager.CreateParticle.angles:type_name -> deadlock.CMsgQAngle
	26, // 27: deadlock.CMsgParticleSystemManager.UpdateParticle.position:type_name -> deadlock.CMsgVector
	26, // 28: deadlock.CMsgParticleSystemManager.UpdateParticleFwd.forward:type_name -> deadlock.CMsgVector
	26, // 29: deadlock.CMsgParticleSystemManager.UpdateParticleOrient.forward:type_name -> deadlock.CMsgVector
	26, // 30: deadlock.CMsgParticleSystemManager.UpdateParticleOrient.left:type_name -> deadlock.CMsgVector
	26, // 31: deadlock.CMsgParticleSystemManager.UpdateParticleOrient.up:type_name -> deadlock.CMsgVector
	26, // 32: deadlock.CMsgParticleSystemManager.UpdateParticleFallback.position:type_name -> deadlock.CMsgVector
	26, // 33: deadlock.CMsgParticleSystemManager.UpdateParticleEnt.fallback_position:type_name -> deadlock.CMsgVector
	26, // 34: deadlock.CMsgParticleSystemManager.UpdateParticleOffset.origin_offset:type_name -> deadlock.CMsgVector
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_citadel_gameevents_proto_init() }
func file_citadel_gameevents_proto_init() {
	if File_citadel_gameevents_proto != nil {
		return
	}
	file_networkbasetypes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_citadel_gameevents_proto_rawDesc), len(file_citadel_gameevents_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_citadel_gameevents_proto_goTypes,
		DependencyIndexes: file_citadel_gameevents_proto_depIdxs,
		EnumInfos:         file_citadel_gameevents_proto_enumTypes,
		MessageInfos:      file_citadel_gameevents_proto_msgTypes,
	}.Build()
	File_citadel_gameevents_proto = out.File
	file_citadel_gameevents_proto_goTypes = nil
	file_citadel_gameevents_proto_depIdxs = nil
}
