// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.6.1
// source: citadel_clientmessages.proto

package deadlock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ECitadelClientMessages int32

const (
	ECitadelClientMessages_CITADEL_CM_MapPing                            ECitadelClientMessages = 1002
	ECitadelClientMessages_CITADEL_CM_PerformanceStats                   ECitadelClientMessages = 1003
	ECitadelClientMessages_CITADEL_CM_PingWheel                          ECitadelClientMessages = 1004
	ECitadelClientMessages_CITADEL_CM_ChatMsg                            ECitadelClientMessages = 1005
	ECitadelClientMessages_CITADEL_CM_PerfReport                         ECitadelClientMessages = 1006
	ECitadelClientMessages_CITADEL_CM_QuickResponse                      ECitadelClientMessages = 1007
	ECitadelClientMessages_CITADEL_CM_Pause                              ECitadelClientMessages = 1008
	ECitadelClientMessages_CITADEL_CM_MapLine                            ECitadelClientMessages = 1009
	ECitadelClientMessages_CITADEL_CM_AbilityPing                        ECitadelClientMessages = 1010
	ECitadelClientMessages_CITADEL_CM_ExecuteMapUnitAbility              ECitadelClientMessages = 1011
	ECitadelClientMessages_CITADEL_CM_GetDamageStats                     ECitadelClientMessages = 1012
	ECitadelClientMessages_CITADEL_CM_CheaterVote                        ECitadelClientMessages = 1013
	ECitadelClientMessages_CITADEL_CM_MutePlayers                        ECitadelClientMessages = 1014
	ECitadelClientMessages_CITADEL_CM_HitMismatch                        ECitadelClientMessages = 1015
	ECitadelClientMessages_CITADEL_CM_HideoutStart                       ECitadelClientMessages = 1016
	ECitadelClientMessages_CITADEL_CM_HeroBuild                          ECitadelClientMessages = 1017
	ECitadelClientMessages_CITADEL_CM_HideoutMenuState                   ECitadelClientMessages = 1018
	ECitadelClientMessages_CITADEL_CM_HideoutSpawn                       ECitadelClientMessages = 1019
	ECitadelClientMessages_CITADEL_CM_HideoutMatchmakingState            ECitadelClientMessages = 1020
	ECitadelClientMessages_CITADEL_CM_PlayerStatsUpdated                 ECitadelClientMessages = 1021
	ECitadelClientMessages_CITADEL_CM_HideoutUpdateHeroReleaseVoteStatus ECitadelClientMessages = 1022
)

// Enum value maps for ECitadelClientMessages.
var (
	ECitadelClientMessages_name = map[int32]string{
		1002: "CITADEL_CM_MapPing",
		1003: "CITADEL_CM_PerformanceStats",
		1004: "CITADEL_CM_PingWheel",
		1005: "CITADEL_CM_ChatMsg",
		1006: "CITADEL_CM_PerfReport",
		1007: "CITADEL_CM_QuickResponse",
		1008: "CITADEL_CM_Pause",
		1009: "CITADEL_CM_MapLine",
		1010: "CITADEL_CM_AbilityPing",
		1011: "CITADEL_CM_ExecuteMapUnitAbility",
		1012: "CITADEL_CM_GetDamageStats",
		1013: "CITADEL_CM_CheaterVote",
		1014: "CITADEL_CM_MutePlayers",
		1015: "CITADEL_CM_HitMismatch",
		1016: "CITADEL_CM_HideoutStart",
		1017: "CITADEL_CM_HeroBuild",
		1018: "CITADEL_CM_HideoutMenuState",
		1019: "CITADEL_CM_HideoutSpawn",
		1020: "CITADEL_CM_HideoutMatchmakingState",
		1021: "CITADEL_CM_PlayerStatsUpdated",
		1022: "CITADEL_CM_HideoutUpdateHeroReleaseVoteStatus",
	}
	ECitadelClientMessages_value = map[string]int32{
		"CITADEL_CM_MapPing":                            1002,
		"CITADEL_CM_PerformanceStats":                   1003,
		"CITADEL_CM_PingWheel":                          1004,
		"CITADEL_CM_ChatMsg":                            1005,
		"CITADEL_CM_PerfReport":                         1006,
		"CITADEL_CM_QuickResponse":                      1007,
		"CITADEL_CM_Pause":                              1008,
		"CITADEL_CM_MapLine":                            1009,
		"CITADEL_CM_AbilityPing":                        1010,
		"CITADEL_CM_ExecuteMapUnitAbility":              1011,
		"CITADEL_CM_GetDamageStats":                     1012,
		"CITADEL_CM_CheaterVote":                        1013,
		"CITADEL_CM_MutePlayers":                        1014,
		"CITADEL_CM_HitMismatch":                        1015,
		"CITADEL_CM_HideoutStart":                       1016,
		"CITADEL_CM_HeroBuild":                          1017,
		"CITADEL_CM_HideoutMenuState":                   1018,
		"CITADEL_CM_HideoutSpawn":                       1019,
		"CITADEL_CM_HideoutMatchmakingState":            1020,
		"CITADEL_CM_PlayerStatsUpdated":                 1021,
		"CITADEL_CM_HideoutUpdateHeroReleaseVoteStatus": 1022,
	}
)

func (x ECitadelClientMessages) Enum() *ECitadelClientMessages {
	p := new(ECitadelClientMessages)
	*p = x
	return p
}

func (x ECitadelClientMessages) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECitadelClientMessages) Descriptor() protoreflect.EnumDescriptor {
	return file_citadel_clientmessages_proto_enumTypes[0].Descriptor()
}

func (ECitadelClientMessages) Type() protoreflect.EnumType {
	return &file_citadel_clientmessages_proto_enumTypes[0]
}

func (x ECitadelClientMessages) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ECitadelClientMessages) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ECitadelClientMessages(num)
	return nil
}

// Deprecated: Use ECitadelClientMessages.Descriptor instead.
func (ECitadelClientMessages) EnumDescriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{0}
}

type CCitadelClientMsg_HideoutMenuState_MenuState int32

const (
	CCitadelClientMsg_HideoutMenuState_k_eNone       CCitadelClientMsg_HideoutMenuState_MenuState = 0
	CCitadelClientMsg_HideoutMenuState_k_eEscapeMenu CCitadelClientMsg_HideoutMenuState_MenuState = 1
	CCitadelClientMsg_HideoutMenuState_k_eDashboard  CCitadelClientMsg_HideoutMenuState_MenuState = 2
)

// Enum value maps for CCitadelClientMsg_HideoutMenuState_MenuState.
var (
	CCitadelClientMsg_HideoutMenuState_MenuState_name = map[int32]string{
		0: "k_eNone",
		1: "k_eEscapeMenu",
		2: "k_eDashboard",
	}
	CCitadelClientMsg_HideoutMenuState_MenuState_value = map[string]int32{
		"k_eNone":       0,
		"k_eEscapeMenu": 1,
		"k_eDashboard":  2,
	}
)

func (x CCitadelClientMsg_HideoutMenuState_MenuState) Enum() *CCitadelClientMsg_HideoutMenuState_MenuState {
	p := new(CCitadelClientMsg_HideoutMenuState_MenuState)
	*p = x
	return p
}

func (x CCitadelClientMsg_HideoutMenuState_MenuState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CCitadelClientMsg_HideoutMenuState_MenuState) Descriptor() protoreflect.EnumDescriptor {
	return file_citadel_clientmessages_proto_enumTypes[1].Descriptor()
}

func (CCitadelClientMsg_HideoutMenuState_MenuState) Type() protoreflect.EnumType {
	return &file_citadel_clientmessages_proto_enumTypes[1]
}

func (x CCitadelClientMsg_HideoutMenuState_MenuState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CCitadelClientMsg_HideoutMenuState_MenuState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CCitadelClientMsg_HideoutMenuState_MenuState(num)
	return nil
}

// Deprecated: Use CCitadelClientMsg_HideoutMenuState_MenuState.Descriptor instead.
func (CCitadelClientMsg_HideoutMenuState_MenuState) EnumDescriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{17, 0}
}

type CCitadelClientMsg_Pause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCitadelClientMsg_Pause) Reset() {
	*x = CCitadelClientMsg_Pause{}
	mi := &file_citadel_clientmessages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_Pause) ProtoMessage() {}

func (x *CCitadelClientMsg_Pause) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_Pause.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_Pause) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{0}
}

type CCitadelClientMsg_MapPing struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PingLocation     *CMsgVector            `protobuf:"bytes,1,opt,name=ping_location,json=pingLocation" json:"ping_location,omitempty"`
	EventType        *int32                 `protobuf:"varint,2,opt,name=event_type,json=eventType" json:"event_type,omitempty"`
	EntityIndex      *int32                 `protobuf:"varint,3,opt,name=entity_index,json=entityIndex,def=-1" json:"entity_index,omitempty"`
	IsAggressivePing *bool                  `protobuf:"varint,4,opt,name=is_aggressive_ping,json=isAggressivePing" json:"is_aggressive_ping,omitempty"`
	IsMinimapPing    *bool                  `protobuf:"varint,5,opt,name=is_minimap_ping,json=isMinimapPing" json:"is_minimap_ping,omitempty"`
	IsBlindPing      *bool                  `protobuf:"varint,6,opt,name=is_blind_ping,json=isBlindPing" json:"is_blind_ping,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for CCitadelClientMsg_MapPing fields.
const (
	Default_CCitadelClientMsg_MapPing_EntityIndex = int32(-1)
)

func (x *CCitadelClientMsg_MapPing) Reset() {
	*x = CCitadelClientMsg_MapPing{}
	mi := &file_citadel_clientmessages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_MapPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_MapPing) ProtoMessage() {}

func (x *CCitadelClientMsg_MapPing) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_MapPing.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_MapPing) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{1}
}

func (x *CCitadelClientMsg_MapPing) GetPingLocation() *CMsgVector {
	if x != nil {
		return x.PingLocation
	}
	return nil
}

func (x *CCitadelClientMsg_MapPing) GetEventType() int32 {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return 0
}

func (x *CCitadelClientMsg_MapPing) GetEntityIndex() int32 {
	if x != nil && x.EntityIndex != nil {
		return *x.EntityIndex
	}
	return Default_CCitadelClientMsg_MapPing_EntityIndex
}

func (x *CCitadelClientMsg_MapPing) GetIsAggressivePing() bool {
	if x != nil && x.IsAggressivePing != nil {
		return *x.IsAggressivePing
	}
	return false
}

func (x *CCitadelClientMsg_MapPing) GetIsMinimapPing() bool {
	if x != nil && x.IsMinimapPing != nil {
		return *x.IsMinimapPing
	}
	return false
}

func (x *CCitadelClientMsg_MapPing) GetIsBlindPing() bool {
	if x != nil && x.IsBlindPing != nil {
		return *x.IsBlindPing
	}
	return false
}

type CCitadelClientMsg_PingWheel struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PingWheelOptionId *uint32                `protobuf:"varint,1,opt,name=ping_wheel_option_id,json=pingWheelOptionId" json:"ping_wheel_option_id,omitempty"`
	SubnavMessageId   *uint32                `protobuf:"varint,2,opt,name=subnav_message_id,json=subnavMessageId" json:"subnav_message_id,omitempty"`
	PingLocation      *CMsgVector            `protobuf:"bytes,3,opt,name=ping_location,json=pingLocation" json:"ping_location,omitempty"`
	EntityIndex       *int32                 `protobuf:"varint,4,opt,name=entity_index,json=entityIndex,def=-1" json:"entity_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

// Default values for CCitadelClientMsg_PingWheel fields.
const (
	Default_CCitadelClientMsg_PingWheel_EntityIndex = int32(-1)
)

func (x *CCitadelClientMsg_PingWheel) Reset() {
	*x = CCitadelClientMsg_PingWheel{}
	mi := &file_citadel_clientmessages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_PingWheel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_PingWheel) ProtoMessage() {}

func (x *CCitadelClientMsg_PingWheel) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_PingWheel.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_PingWheel) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{2}
}

func (x *CCitadelClientMsg_PingWheel) GetPingWheelOptionId() uint32 {
	if x != nil && x.PingWheelOptionId != nil {
		return *x.PingWheelOptionId
	}
	return 0
}

func (x *CCitadelClientMsg_PingWheel) GetSubnavMessageId() uint32 {
	if x != nil && x.SubnavMessageId != nil {
		return *x.SubnavMessageId
	}
	return 0
}

func (x *CCitadelClientMsg_PingWheel) GetPingLocation() *CMsgVector {
	if x != nil {
		return x.PingLocation
	}
	return nil
}

func (x *CCitadelClientMsg_PingWheel) GetEntityIndex() int32 {
	if x != nil && x.EntityIndex != nil {
		return *x.EntityIndex
	}
	return Default_CCitadelClientMsg_PingWheel_EntityIndex
}

type CCitadelClientMsg_AbilityPing struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EntityIndex      *int32                 `protobuf:"varint,1,opt,name=entity_index,json=entityIndex,def=-1" json:"entity_index,omitempty"`
	PingedAbilityId  *uint32                `protobuf:"varint,2,opt,name=pinged_ability_id,json=pingedAbilityId" json:"pinged_ability_id,omitempty"`
	PingedPlayerSlot *int32                 `protobuf:"varint,3,opt,name=pinged_player_slot,json=pingedPlayerSlot,def=-1" json:"pinged_player_slot,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for CCitadelClientMsg_AbilityPing fields.
const (
	Default_CCitadelClientMsg_AbilityPing_EntityIndex      = int32(-1)
	Default_CCitadelClientMsg_AbilityPing_PingedPlayerSlot = int32(-1)
)

func (x *CCitadelClientMsg_AbilityPing) Reset() {
	*x = CCitadelClientMsg_AbilityPing{}
	mi := &file_citadel_clientmessages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_AbilityPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_AbilityPing) ProtoMessage() {}

func (x *CCitadelClientMsg_AbilityPing) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_AbilityPing.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_AbilityPing) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{3}
}

func (x *CCitadelClientMsg_AbilityPing) GetEntityIndex() int32 {
	if x != nil && x.EntityIndex != nil {
		return *x.EntityIndex
	}
	return Default_CCitadelClientMsg_AbilityPing_EntityIndex
}

func (x *CCitadelClientMsg_AbilityPing) GetPingedAbilityId() uint32 {
	if x != nil && x.PingedAbilityId != nil {
		return *x.PingedAbilityId
	}
	return 0
}

func (x *CCitadelClientMsg_AbilityPing) GetPingedPlayerSlot() int32 {
	if x != nil && x.PingedPlayerSlot != nil {
		return *x.PingedPlayerSlot
	}
	return Default_CCitadelClientMsg_AbilityPing_PingedPlayerSlot
}

type CCitadelClientMsg_MapLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mapline       *CMsgMapLine           `protobuf:"bytes,1,opt,name=mapline" json:"mapline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCitadelClientMsg_MapLine) Reset() {
	*x = CCitadelClientMsg_MapLine{}
	mi := &file_citadel_clientmessages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_MapLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_MapLine) ProtoMessage() {}

func (x *CCitadelClientMsg_MapLine) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_MapLine.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_MapLine) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{4}
}

func (x *CCitadelClientMsg_MapLine) GetMapline() *CMsgMapLine {
	if x != nil {
		return x.Mapline
	}
	return nil
}

type CCitadelClientMsg_QuickResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PingWheelMessageId        *uint32                `protobuf:"varint,1,opt,name=ping_wheel_message_id,json=pingWheelMessageId" json:"ping_wheel_message_id,omitempty"`
	RespondingToPingMessageId *uint32                `protobuf:"varint,2,opt,name=responding_to_ping_message_id,json=respondingToPingMessageId" json:"responding_to_ping_message_id,omitempty"`
	RespondingToPlayerSlot    *int32                 `protobuf:"varint,3,opt,name=responding_to_player_slot,json=respondingToPlayerSlot,def=-1" json:"responding_to_player_slot,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

// Default values for CCitadelClientMsg_QuickResponse fields.
const (
	Default_CCitadelClientMsg_QuickResponse_RespondingToPlayerSlot = int32(-1)
)

func (x *CCitadelClientMsg_QuickResponse) Reset() {
	*x = CCitadelClientMsg_QuickResponse{}
	mi := &file_citadel_clientmessages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_QuickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_QuickResponse) ProtoMessage() {}

func (x *CCitadelClientMsg_QuickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_QuickResponse.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_QuickResponse) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{5}
}

func (x *CCitadelClientMsg_QuickResponse) GetPingWheelMessageId() uint32 {
	if x != nil && x.PingWheelMessageId != nil {
		return *x.PingWheelMessageId
	}
	return 0
}

func (x *CCitadelClientMsg_QuickResponse) GetRespondingToPingMessageId() uint32 {
	if x != nil && x.RespondingToPingMessageId != nil {
		return *x.RespondingToPingMessageId
	}
	return 0
}

func (x *CCitadelClientMsg_QuickResponse) GetRespondingToPlayerSlot() int32 {
	if x != nil && x.RespondingToPlayerSlot != nil {
		return *x.RespondingToPlayerSlot
	}
	return Default_CCitadelClientMsg_QuickResponse_RespondingToPlayerSlot
}

type CCitadelClientMsg_PerformanceStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentGameTime *float32               `protobuf:"fixed32,1,opt,name=current_game_time,json=currentGameTime" json:"current_game_time,omitempty"`
	AverageFps      *float32               `protobuf:"fixed32,2,opt,name=average_fps,json=averageFps" json:"average_fps,omitempty"`
	MinFps          *float32               `protobuf:"fixed32,3,opt,name=min_fps,json=minFps" json:"min_fps,omitempty"`
	MaxFps          *float32               `protobuf:"fixed32,4,opt,name=max_fps,json=maxFps" json:"max_fps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CCitadelClientMsg_PerformanceStats) Reset() {
	*x = CCitadelClientMsg_PerformanceStats{}
	mi := &file_citadel_clientmessages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_PerformanceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_PerformanceStats) ProtoMessage() {}

func (x *CCitadelClientMsg_PerformanceStats) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_PerformanceStats.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_PerformanceStats) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{6}
}

func (x *CCitadelClientMsg_PerformanceStats) GetCurrentGameTime() float32 {
	if x != nil && x.CurrentGameTime != nil {
		return *x.CurrentGameTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerformanceStats) GetAverageFps() float32 {
	if x != nil && x.AverageFps != nil {
		return *x.AverageFps
	}
	return 0
}

func (x *CCitadelClientMsg_PerformanceStats) GetMinFps() float32 {
	if x != nil && x.MinFps != nil {
		return *x.MinFps
	}
	return 0
}

func (x *CCitadelClientMsg_PerformanceStats) GetMaxFps() float32 {
	if x != nil && x.MaxFps != nil {
		return *x.MaxFps
	}
	return 0
}

type CCitadelClientMsg_ChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatText      *string                `protobuf:"bytes,1,opt,name=chat_text,json=chatText" json:"chat_text,omitempty"`
	AllChat       *bool                  `protobuf:"varint,2,opt,name=all_chat,json=allChat" json:"all_chat,omitempty"`
	LaneColor     *CMsgLaneColor         `protobuf:"varint,3,opt,name=lane_color,json=laneColor,enum=deadlock.CMsgLaneColor,def=0" json:"lane_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CCitadelClientMsg_ChatMsg fields.
const (
	Default_CCitadelClientMsg_ChatMsg_LaneColor = CMsgLaneColor_k_ELaneColor_Invalid
)

func (x *CCitadelClientMsg_ChatMsg) Reset() {
	*x = CCitadelClientMsg_ChatMsg{}
	mi := &file_citadel_clientmessages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_ChatMsg) ProtoMessage() {}

func (x *CCitadelClientMsg_ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_ChatMsg.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_ChatMsg) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{7}
}

func (x *CCitadelClientMsg_ChatMsg) GetChatText() string {
	if x != nil && x.ChatText != nil {
		return *x.ChatText
	}
	return ""
}

func (x *CCitadelClientMsg_ChatMsg) GetAllChat() bool {
	if x != nil && x.AllChat != nil {
		return *x.AllChat
	}
	return false
}

func (x *CCitadelClientMsg_ChatMsg) GetLaneColor() CMsgLaneColor {
	if x != nil && x.LaneColor != nil {
		return *x.LaneColor
	}
	return Default_CCitadelClientMsg_ChatMsg_LaneColor
}

type CCitadelClientMsg_PerfReport struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	AverageFrameTime                      *float32               `protobuf:"fixed32,1,opt,name=average_frame_time,json=averageFrameTime" json:"average_frame_time,omitempty"`
	MaxFrameTime                          *float32               `protobuf:"fixed32,2,opt,name=max_frame_time,json=maxFrameTime" json:"max_frame_time,omitempty"`
	AverageComputeTime                    *float32               `protobuf:"fixed32,3,opt,name=average_compute_time,json=averageComputeTime" json:"average_compute_time,omitempty"`
	MaxComputeTime                        *float32               `protobuf:"fixed32,4,opt,name=max_compute_time,json=maxComputeTime" json:"max_compute_time,omitempty"`
	AverageClientTickTime                 *float32               `protobuf:"fixed32,5,opt,name=average_client_tick_time,json=averageClientTickTime" json:"average_client_tick_time,omitempty"`
	MaxClientTickTime                     *float32               `protobuf:"fixed32,6,opt,name=max_client_tick_time,json=maxClientTickTime" json:"max_client_tick_time,omitempty"`
	AverageClientSimulateTime             *float32               `protobuf:"fixed32,7,opt,name=average_client_simulate_time,json=averageClientSimulateTime" json:"average_client_simulate_time,omitempty"`
	MaxClientSimulateTime                 *float32               `protobuf:"fixed32,8,opt,name=max_client_simulate_time,json=maxClientSimulateTime" json:"max_client_simulate_time,omitempty"`
	AverageOutputTime                     *float32               `protobuf:"fixed32,9,opt,name=average_output_time,json=averageOutputTime" json:"average_output_time,omitempty"`
	MaxOutputTime                         *float32               `protobuf:"fixed32,10,opt,name=max_output_time,json=maxOutputTime" json:"max_output_time,omitempty"`
	AverageWaitForRenderingToCompleteTime *float32               `protobuf:"fixed32,11,opt,name=average_wait_for_rendering_to_complete_time,json=averageWaitForRenderingToCompleteTime" json:"average_wait_for_rendering_to_complete_time,omitempty"`
	MaxWaitForRenderingToCompleteTime     *float32               `protobuf:"fixed32,12,opt,name=max_wait_for_rendering_to_complete_time,json=maxWaitForRenderingToCompleteTime" json:"max_wait_for_rendering_to_complete_time,omitempty"`
	AverageSwapTime                       *float32               `protobuf:"fixed32,13,opt,name=average_swap_time,json=averageSwapTime" json:"average_swap_time,omitempty"`
	MaxSwapTime                           *float32               `protobuf:"fixed32,14,opt,name=max_swap_time,json=maxSwapTime" json:"max_swap_time,omitempty"`
	AverageFrameUpdateTime                *float32               `protobuf:"fixed32,15,opt,name=average_frame_update_time,json=averageFrameUpdateTime" json:"average_frame_update_time,omitempty"`
	MaxFrameUpdateTime                    *float32               `protobuf:"fixed32,16,opt,name=max_frame_update_time,json=maxFrameUpdateTime" json:"max_frame_update_time,omitempty"`
	AverageIdleTime                       *float32               `protobuf:"fixed32,17,opt,name=average_idle_time,json=averageIdleTime" json:"average_idle_time,omitempty"`
	MaxIdleTime                           *float32               `protobuf:"fixed32,18,opt,name=max_idle_time,json=maxIdleTime" json:"max_idle_time,omitempty"`
	AverageInputProcessingTime            *float32               `protobuf:"fixed32,19,opt,name=average_input_processing_time,json=averageInputProcessingTime" json:"average_input_processing_time,omitempty"`
	MaxInputProcessingTime                *float32               `protobuf:"fixed32,20,opt,name=max_input_processing_time,json=maxInputProcessingTime" json:"max_input_processing_time,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *CCitadelClientMsg_PerfReport) Reset() {
	*x = CCitadelClientMsg_PerfReport{}
	mi := &file_citadel_clientmessages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_PerfReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_PerfReport) ProtoMessage() {}

func (x *CCitadelClientMsg_PerfReport) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_PerfReport.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_PerfReport) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{8}
}

func (x *CCitadelClientMsg_PerfReport) GetAverageFrameTime() float32 {
	if x != nil && x.AverageFrameTime != nil {
		return *x.AverageFrameTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxFrameTime() float32 {
	if x != nil && x.MaxFrameTime != nil {
		return *x.MaxFrameTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetAverageComputeTime() float32 {
	if x != nil && x.AverageComputeTime != nil {
		return *x.AverageComputeTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxComputeTime() float32 {
	if x != nil && x.MaxComputeTime != nil {
		return *x.MaxComputeTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetAverageClientTickTime() float32 {
	if x != nil && x.AverageClientTickTime != nil {
		return *x.AverageClientTickTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxClientTickTime() float32 {
	if x != nil && x.MaxClientTickTime != nil {
		return *x.MaxClientTickTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetAverageClientSimulateTime() float32 {
	if x != nil && x.AverageClientSimulateTime != nil {
		return *x.AverageClientSimulateTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxClientSimulateTime() float32 {
	if x != nil && x.MaxClientSimulateTime != nil {
		return *x.MaxClientSimulateTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetAverageOutputTime() float32 {
	if x != nil && x.AverageOutputTime != nil {
		return *x.AverageOutputTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxOutputTime() float32 {
	if x != nil && x.MaxOutputTime != nil {
		return *x.MaxOutputTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetAverageWaitForRenderingToCompleteTime() float32 {
	if x != nil && x.AverageWaitForRenderingToCompleteTime != nil {
		return *x.AverageWaitForRenderingToCompleteTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxWaitForRenderingToCompleteTime() float32 {
	if x != nil && x.MaxWaitForRenderingToCompleteTime != nil {
		return *x.MaxWaitForRenderingToCompleteTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetAverageSwapTime() float32 {
	if x != nil && x.AverageSwapTime != nil {
		return *x.AverageSwapTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxSwapTime() float32 {
	if x != nil && x.MaxSwapTime != nil {
		return *x.MaxSwapTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetAverageFrameUpdateTime() float32 {
	if x != nil && x.AverageFrameUpdateTime != nil {
		return *x.AverageFrameUpdateTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxFrameUpdateTime() float32 {
	if x != nil && x.MaxFrameUpdateTime != nil {
		return *x.MaxFrameUpdateTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetAverageIdleTime() float32 {
	if x != nil && x.AverageIdleTime != nil {
		return *x.AverageIdleTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxIdleTime() float32 {
	if x != nil && x.MaxIdleTime != nil {
		return *x.MaxIdleTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetAverageInputProcessingTime() float32 {
	if x != nil && x.AverageInputProcessingTime != nil {
		return *x.AverageInputProcessingTime
	}
	return 0
}

func (x *CCitadelClientMsg_PerfReport) GetMaxInputProcessingTime() float32 {
	if x != nil && x.MaxInputProcessingTime != nil {
		return *x.MaxInputProcessingTime
	}
	return 0
}

type CCitadelClientMsg_GetDamageStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LobbyPlayerSlot *uint32                `protobuf:"varint,1,opt,name=lobby_player_slot,json=lobbyPlayerSlot" json:"lobby_player_slot,omitempty"`
	AbilityName     *string                `protobuf:"bytes,2,opt,name=ability_name,json=abilityName" json:"ability_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CCitadelClientMsg_GetDamageStats) Reset() {
	*x = CCitadelClientMsg_GetDamageStats{}
	mi := &file_citadel_clientmessages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_GetDamageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_GetDamageStats) ProtoMessage() {}

func (x *CCitadelClientMsg_GetDamageStats) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_GetDamageStats.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_GetDamageStats) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{9}
}

func (x *CCitadelClientMsg_GetDamageStats) GetLobbyPlayerSlot() uint32 {
	if x != nil && x.LobbyPlayerSlot != nil {
		return *x.LobbyPlayerSlot
	}
	return 0
}

func (x *CCitadelClientMsg_GetDamageStats) GetAbilityName() string {
	if x != nil && x.AbilityName != nil {
		return *x.AbilityName
	}
	return ""
}

type CCitadelClientCachedPlayerStats struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Version       *uint32                                 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Stats         []*CCitadelClientCachedPlayerStats_Stat `protobuf:"bytes,2,rep,name=stats" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCitadelClientCachedPlayerStats) Reset() {
	*x = CCitadelClientCachedPlayerStats{}
	mi := &file_citadel_clientmessages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientCachedPlayerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientCachedPlayerStats) ProtoMessage() {}

func (x *CCitadelClientCachedPlayerStats) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientCachedPlayerStats.ProtoReflect.Descriptor instead.
func (*CCitadelClientCachedPlayerStats) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{10}
}

func (x *CCitadelClientCachedPlayerStats) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *CCitadelClientCachedPlayerStats) GetStats() []*CCitadelClientCachedPlayerStats_Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type CCitadelClientMsg_ExecuteMapUnitAbility struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AbilityEntityIndex *int32                 `protobuf:"varint,1,opt,name=ability_entity_index,json=abilityEntityIndex" json:"ability_entity_index,omitempty"`
	TargetEntityIndex  *int32                 `protobuf:"varint,2,opt,name=target_entity_index,json=targetEntityIndex" json:"target_entity_index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CCitadelClientMsg_ExecuteMapUnitAbility) Reset() {
	*x = CCitadelClientMsg_ExecuteMapUnitAbility{}
	mi := &file_citadel_clientmessages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_ExecuteMapUnitAbility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_ExecuteMapUnitAbility) ProtoMessage() {}

func (x *CCitadelClientMsg_ExecuteMapUnitAbility) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_ExecuteMapUnitAbility.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_ExecuteMapUnitAbility) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{11}
}

func (x *CCitadelClientMsg_ExecuteMapUnitAbility) GetAbilityEntityIndex() int32 {
	if x != nil && x.AbilityEntityIndex != nil {
		return *x.AbilityEntityIndex
	}
	return 0
}

func (x *CCitadelClientMsg_ExecuteMapUnitAbility) GetTargetEntityIndex() int32 {
	if x != nil && x.TargetEntityIndex != nil {
		return *x.TargetEntityIndex
	}
	return 0
}

type CCitadelClientMsg_CheaterVote struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EndGameImmediately *bool                  `protobuf:"varint,1,opt,name=end_game_immediately,json=endGameImmediately" json:"end_game_immediately,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CCitadelClientMsg_CheaterVote) Reset() {
	*x = CCitadelClientMsg_CheaterVote{}
	mi := &file_citadel_clientmessages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_CheaterVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_CheaterVote) ProtoMessage() {}

func (x *CCitadelClientMsg_CheaterVote) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_CheaterVote.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_CheaterVote) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{12}
}

func (x *CCitadelClientMsg_CheaterVote) GetEndGameImmediately() bool {
	if x != nil && x.EndGameImmediately != nil {
		return *x.EndGameImmediately
	}
	return false
}

type CCitadelClientMsg_MutePlayers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerSlots   []int32                `protobuf:"varint,1,rep,name=player_slots,json=playerSlots" json:"player_slots,omitempty"`
	Unmute        *bool                  `protobuf:"varint,2,opt,name=unmute" json:"unmute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCitadelClientMsg_MutePlayers) Reset() {
	*x = CCitadelClientMsg_MutePlayers{}
	mi := &file_citadel_clientmessages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_MutePlayers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_MutePlayers) ProtoMessage() {}

func (x *CCitadelClientMsg_MutePlayers) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_MutePlayers.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_MutePlayers) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{13}
}

func (x *CCitadelClientMsg_MutePlayers) GetPlayerSlots() []int32 {
	if x != nil {
		return x.PlayerSlots
	}
	return nil
}

func (x *CCitadelClientMsg_MutePlayers) GetUnmute() bool {
	if x != nil && x.Unmute != nil {
		return *x.Unmute
	}
	return false
}

type CCitadelClientMsg_HitMismatch struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientHitEntityIndex *int32                 `protobuf:"varint,1,opt,name=client_hit_entity_index,json=clientHitEntityIndex,def=-1" json:"client_hit_entity_index,omitempty"`
	ServerHitEntityIndex *int32                 `protobuf:"varint,2,opt,name=server_hit_entity_index,json=serverHitEntityIndex,def=-1" json:"server_hit_entity_index,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

// Default values for CCitadelClientMsg_HitMismatch fields.
const (
	Default_CCitadelClientMsg_HitMismatch_ClientHitEntityIndex = int32(-1)
	Default_CCitadelClientMsg_HitMismatch_ServerHitEntityIndex = int32(-1)
)

func (x *CCitadelClientMsg_HitMismatch) Reset() {
	*x = CCitadelClientMsg_HitMismatch{}
	mi := &file_citadel_clientmessages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_HitMismatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_HitMismatch) ProtoMessage() {}

func (x *CCitadelClientMsg_HitMismatch) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_HitMismatch.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_HitMismatch) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{14}
}

func (x *CCitadelClientMsg_HitMismatch) GetClientHitEntityIndex() int32 {
	if x != nil && x.ClientHitEntityIndex != nil {
		return *x.ClientHitEntityIndex
	}
	return Default_CCitadelClientMsg_HitMismatch_ClientHitEntityIndex
}

func (x *CCitadelClientMsg_HitMismatch) GetServerHitEntityIndex() int32 {
	if x != nil && x.ServerHitEntityIndex != nil {
		return *x.ServerHitEntityIndex
	}
	return Default_CCitadelClientMsg_HitMismatch_ServerHitEntityIndex
}

type CCitadelClientMsg_HideoutStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCitadelClientMsg_HideoutStart) Reset() {
	*x = CCitadelClientMsg_HideoutStart{}
	mi := &file_citadel_clientmessages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_HideoutStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_HideoutStart) ProtoMessage() {}

func (x *CCitadelClientMsg_HideoutStart) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_HideoutStart.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_HideoutStart) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{15}
}

type CCitadelClientMsg_HeroBuild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeroBuild     *CMsgHeroBuild         `protobuf:"bytes,1,opt,name=hero_build,json=heroBuild" json:"hero_build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCitadelClientMsg_HeroBuild) Reset() {
	*x = CCitadelClientMsg_HeroBuild{}
	mi := &file_citadel_clientmessages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_HeroBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_HeroBuild) ProtoMessage() {}

func (x *CCitadelClientMsg_HeroBuild) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_HeroBuild.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_HeroBuild) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{16}
}

func (x *CCitadelClientMsg_HeroBuild) GetHeroBuild() *CMsgHeroBuild {
	if x != nil {
		return x.HeroBuild
	}
	return nil
}

type CCitadelClientMsg_HideoutMenuState struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	MenuState     *CCitadelClientMsg_HideoutMenuState_MenuState `protobuf:"varint,1,opt,name=menu_state,json=menuState,enum=deadlock.CCitadelClientMsg_HideoutMenuState_MenuState,def=0" json:"menu_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CCitadelClientMsg_HideoutMenuState fields.
const (
	Default_CCitadelClientMsg_HideoutMenuState_MenuState = CCitadelClientMsg_HideoutMenuState_k_eNone
)

func (x *CCitadelClientMsg_HideoutMenuState) Reset() {
	*x = CCitadelClientMsg_HideoutMenuState{}
	mi := &file_citadel_clientmessages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_HideoutMenuState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_HideoutMenuState) ProtoMessage() {}

func (x *CCitadelClientMsg_HideoutMenuState) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_HideoutMenuState.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_HideoutMenuState) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{17}
}

func (x *CCitadelClientMsg_HideoutMenuState) GetMenuState() CCitadelClientMsg_HideoutMenuState_MenuState {
	if x != nil && x.MenuState != nil {
		return *x.MenuState
	}
	return Default_CCitadelClientMsg_HideoutMenuState_MenuState
}

type CCitadelClientMsg_HideoutSpawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeroId        *uint32                `protobuf:"varint,1,opt,name=hero_id,json=heroId" json:"hero_id,omitempty"`
	ShowIntro     *bool                  `protobuf:"varint,2,opt,name=show_intro,json=showIntro" json:"show_intro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCitadelClientMsg_HideoutSpawn) Reset() {
	*x = CCitadelClientMsg_HideoutSpawn{}
	mi := &file_citadel_clientmessages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_HideoutSpawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_HideoutSpawn) ProtoMessage() {}

func (x *CCitadelClientMsg_HideoutSpawn) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_HideoutSpawn.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_HideoutSpawn) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{18}
}

func (x *CCitadelClientMsg_HideoutSpawn) GetHeroId() uint32 {
	if x != nil && x.HeroId != nil {
		return *x.HeroId
	}
	return 0
}

func (x *CCitadelClientMsg_HideoutSpawn) GetShowIntro() bool {
	if x != nil && x.ShowIntro != nil {
		return *x.ShowIntro
	}
	return false
}

type CCitadelClientMsg_HideoutMatchmakingState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMatchmaking *bool                  `protobuf:"varint,1,opt,name=is_matchmaking,json=isMatchmaking" json:"is_matchmaking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCitadelClientMsg_HideoutMatchmakingState) Reset() {
	*x = CCitadelClientMsg_HideoutMatchmakingState{}
	mi := &file_citadel_clientmessages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_HideoutMatchmakingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_HideoutMatchmakingState) ProtoMessage() {}

func (x *CCitadelClientMsg_HideoutMatchmakingState) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_HideoutMatchmakingState.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_HideoutMatchmakingState) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{19}
}

func (x *CCitadelClientMsg_HideoutMatchmakingState) GetIsMatchmaking() bool {
	if x != nil && x.IsMatchmaking != nil {
		return *x.IsMatchmaking
	}
	return false
}

type CCitadelClientMsg_PlayerStatsUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCitadelClientMsg_PlayerStatsUpdated) Reset() {
	*x = CCitadelClientMsg_PlayerStatsUpdated{}
	mi := &file_citadel_clientmessages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_PlayerStatsUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_PlayerStatsUpdated) ProtoMessage() {}

func (x *CCitadelClientMsg_PlayerStatsUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_PlayerStatsUpdated.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_PlayerStatsUpdated) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{20}
}

type CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VotesCastTotal *uint32                `protobuf:"varint,1,opt,name=votes_cast_total,json=votesCastTotal" json:"votes_cast_total,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus) Reset() {
	*x = CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus{}
	mi := &file_citadel_clientmessages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus) ProtoMessage() {}

func (x *CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus.ProtoReflect.Descriptor instead.
func (*CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{21}
}

func (x *CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus) GetVotesCastTotal() uint32 {
	if x != nil && x.VotesCastTotal != nil {
		return *x.VotesCastTotal
	}
	return 0
}

type CCitadelClientCachedPlayerStats_Stat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StatName        *string                `protobuf:"bytes,1,opt,name=stat_name,json=statName" json:"stat_name,omitempty"`
	AllTimeTotal    *uint64                `protobuf:"varint,2,opt,name=all_time_total,json=allTimeTotal" json:"all_time_total,omitempty"`
	AllTimeMatchMax *uint32                `protobuf:"varint,3,opt,name=all_time_match_max,json=allTimeMatchMax" json:"all_time_match_max,omitempty"`
	AllTimeLifeMax  *uint32                `protobuf:"varint,4,opt,name=all_time_life_max,json=allTimeLifeMax" json:"all_time_life_max,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CCitadelClientCachedPlayerStats_Stat) Reset() {
	*x = CCitadelClientCachedPlayerStats_Stat{}
	mi := &file_citadel_clientmessages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelClientCachedPlayerStats_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelClientCachedPlayerStats_Stat) ProtoMessage() {}

func (x *CCitadelClientCachedPlayerStats_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_clientmessages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelClientCachedPlayerStats_Stat.ProtoReflect.Descriptor instead.
func (*CCitadelClientCachedPlayerStats_Stat) Descriptor() ([]byte, []int) {
	return file_citadel_clientmessages_proto_rawDescGZIP(), []int{10, 0}
}

func (x *CCitadelClientCachedPlayerStats_Stat) GetStatName() string {
	if x != nil && x.StatName != nil {
		return *x.StatName
	}
	return ""
}

func (x *CCitadelClientCachedPlayerStats_Stat) GetAllTimeTotal() uint64 {
	if x != nil && x.AllTimeTotal != nil {
		return *x.AllTimeTotal
	}
	return 0
}

func (x *CCitadelClientCachedPlayerStats_Stat) GetAllTimeMatchMax() uint32 {
	if x != nil && x.AllTimeMatchMax != nil {
		return *x.AllTimeMatchMax
	}
	return 0
}

func (x *CCitadelClientCachedPlayerStats_Stat) GetAllTimeLifeMax() uint32 {
	if x != nil && x.AllTimeLifeMax != nil {
		return *x.AllTimeLifeMax
	}
	return 0
}

var File_citadel_clientmessages_proto protoreflect.FileDescriptor

const file_citadel_clientmessages_proto_rawDesc = "" +
	"\n" +
	"\x1ccitadel_clientmessages.proto\x12\bdeadlock\x1a\x16networkbasetypes.proto\x1a\x1fcitadel_gcmessages_common.proto\"\x19\n" +
	"\x17CCitadelClientMsg_Pause\"\x96\x02\n" +
	"\x19CCitadelClientMsg_MapPing\x129\n" +
	"\rping_location\x18\x01 \x01(\v2\x14.deadlock.CMsgVectorR\fpingLocation\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x05R\teventType\x12%\n" +
	"\fentity_index\x18\x03 \x01(\x05:\x02-1R\ventityIndex\x12,\n" +
	"\x12is_aggressive_ping\x18\x04 \x01(\bR\x10isAggressivePing\x12&\n" +
	"\x0fis_minimap_ping\x18\x05 \x01(\bR\risMinimapPing\x12\"\n" +
	"\ris_blind_ping\x18\x06 \x01(\bR\visBlindPing\"\xdc\x01\n" +
	"\x1bCCitadelClientMsg_PingWheel\x12/\n" +
	"\x14ping_wheel_option_id\x18\x01 \x01(\rR\x11pingWheelOptionId\x12*\n" +
	"\x11subnav_message_id\x18\x02 \x01(\rR\x0fsubnavMessageId\x129\n" +
	"\rping_location\x18\x03 \x01(\v2\x14.deadlock.CMsgVectorR\fpingLocation\x12%\n" +
	"\fentity_index\x18\x04 \x01(\x05:\x02-1R\ventityIndex\"\xa4\x01\n" +
	"\x1dCCitadelClientMsg_AbilityPing\x12%\n" +
	"\fentity_index\x18\x01 \x01(\x05:\x02-1R\ventityIndex\x12*\n" +
	"\x11pinged_ability_id\x18\x02 \x01(\rR\x0fpingedAbilityId\x120\n" +
	"\x12pinged_player_slot\x18\x03 \x01(\x05:\x02-1R\x10pingedPlayerSlot\"L\n" +
	"\x19CCitadelClientMsg_MapLine\x12/\n" +
	"\amapline\x18\x01 \x01(\v2\x15.deadlock.CMsgMapLineR\amapline\"\xd5\x01\n" +
	"\x1fCCitadelClientMsg_QuickResponse\x121\n" +
	"\x15ping_wheel_message_id\x18\x01 \x01(\rR\x12pingWheelMessageId\x12@\n" +
	"\x1dresponding_to_ping_message_id\x18\x02 \x01(\rR\x19respondingToPingMessageId\x12=\n" +
	"\x19responding_to_player_slot\x18\x03 \x01(\x05:\x02-1R\x16respondingToPlayerSlot\"\xa3\x01\n" +
	"\"CCitadelClientMsg_PerformanceStats\x12*\n" +
	"\x11current_game_time\x18\x01 \x01(\x02R\x0fcurrentGameTime\x12\x1f\n" +
	"\vaverage_fps\x18\x02 \x01(\x02R\n" +
	"averageFps\x12\x17\n" +
	"\amin_fps\x18\x03 \x01(\x02R\x06minFps\x12\x17\n" +
	"\amax_fps\x18\x04 \x01(\x02R\x06maxFps\"\xa1\x01\n" +
	"\x19CCitadelClientMsg_ChatMsg\x12\x1b\n" +
	"\tchat_text\x18\x01 \x01(\tR\bchatText\x12\x19\n" +
	"\ball_chat\x18\x02 \x01(\bR\aallChat\x12L\n" +
	"\n" +
	"lane_color\x18\x03 \x01(\x0e2\x17.deadlock.CMsgLaneColor:\x14k_ELaneColor_InvalidR\tlaneColor\"\xc6\b\n" +
	"\x1cCCitadelClientMsg_PerfReport\x12,\n" +
	"\x12average_frame_time\x18\x01 \x01(\x02R\x10averageFrameTime\x12$\n" +
	"\x0emax_frame_time\x18\x02 \x01(\x02R\fmaxFrameTime\x120\n" +
	"\x14average_compute_time\x18\x03 \x01(\x02R\x12averageComputeTime\x12(\n" +
	"\x10max_compute_time\x18\x04 \x01(\x02R\x0emaxComputeTime\x127\n" +
	"\x18average_client_tick_time\x18\x05 \x01(\x02R\x15averageClientTickTime\x12/\n" +
	"\x14max_client_tick_time\x18\x06 \x01(\x02R\x11maxClientTickTime\x12?\n" +
	"\x1caverage_client_simulate_time\x18\a \x01(\x02R\x19averageClientSimulateTime\x127\n" +
	"\x18max_client_simulate_time\x18\b \x01(\x02R\x15maxClientSimulateTime\x12.\n" +
	"\x13average_output_time\x18\t \x01(\x02R\x11averageOutputTime\x12&\n" +
	"\x0fmax_output_time\x18\n" +
	" \x01(\x02R\rmaxOutputTime\x12Z\n" +
	"+average_wait_for_rendering_to_complete_time\x18\v \x01(\x02R%averageWaitForRenderingToCompleteTime\x12R\n" +
	"'max_wait_for_rendering_to_complete_time\x18\f \x01(\x02R!maxWaitForRenderingToCompleteTime\x12*\n" +
	"\x11average_swap_time\x18\r \x01(\x02R\x0faverageSwapTime\x12\"\n" +
	"\rmax_swap_time\x18\x0e \x01(\x02R\vmaxSwapTime\x129\n" +
	"\x19average_frame_update_time\x18\x0f \x01(\x02R\x16averageFrameUpdateTime\x121\n" +
	"\x15max_frame_update_time\x18\x10 \x01(\x02R\x12maxFrameUpdateTime\x12*\n" +
	"\x11average_idle_time\x18\x11 \x01(\x02R\x0faverageIdleTime\x12\"\n" +
	"\rmax_idle_time\x18\x12 \x01(\x02R\vmaxIdleTime\x12A\n" +
	"\x1daverage_input_processing_time\x18\x13 \x01(\x02R\x1aaverageInputProcessingTime\x129\n" +
	"\x19max_input_processing_time\x18\x14 \x01(\x02R\x16maxInputProcessingTime\"q\n" +
	" CCitadelClientMsg_GetDamageStats\x12*\n" +
	"\x11lobby_player_slot\x18\x01 \x01(\rR\x0flobbyPlayerSlot\x12!\n" +
	"\fability_name\x18\x02 \x01(\tR\vabilityName\"\xa5\x02\n" +
	"\x1fCCitadelClientCachedPlayerStats\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12D\n" +
	"\x05stats\x18\x02 \x03(\v2..deadlock.CCitadelClientCachedPlayerStats.StatR\x05stats\x1a\xa1\x01\n" +
	"\x04Stat\x12\x1b\n" +
	"\tstat_name\x18\x01 \x01(\tR\bstatName\x12$\n" +
	"\x0eall_time_total\x18\x02 \x01(\x04R\fallTimeTotal\x12+\n" +
	"\x12all_time_match_max\x18\x03 \x01(\rR\x0fallTimeMatchMax\x12)\n" +
	"\x11all_time_life_max\x18\x04 \x01(\rR\x0eallTimeLifeMax\"\x8b\x01\n" +
	"'CCitadelClientMsg_ExecuteMapUnitAbility\x120\n" +
	"\x14ability_entity_index\x18\x01 \x01(\x05R\x12abilityEntityIndex\x12.\n" +
	"\x13target_entity_index\x18\x02 \x01(\x05R\x11targetEntityIndex\"Q\n" +
	"\x1dCCitadelClientMsg_CheaterVote\x120\n" +
	"\x14end_game_immediately\x18\x01 \x01(\bR\x12endGameImmediately\"Z\n" +
	"\x1dCCitadelClientMsg_MutePlayers\x12!\n" +
	"\fplayer_slots\x18\x01 \x03(\x05R\vplayerSlots\x12\x16\n" +
	"\x06unmute\x18\x02 \x01(\bR\x06unmute\"\x95\x01\n" +
	"\x1dCCitadelClientMsg_HitMismatch\x129\n" +
	"\x17client_hit_entity_index\x18\x01 \x01(\x05:\x02-1R\x14clientHitEntityIndex\x129\n" +
	"\x17server_hit_entity_index\x18\x02 \x01(\x05:\x02-1R\x14serverHitEntityIndex\" \n" +
	"\x1eCCitadelClientMsg_HideoutStart\"U\n" +
	"\x1bCCitadelClientMsg_HeroBuild\x126\n" +
	"\n" +
	"hero_build\x18\x01 \x01(\v2\x17.deadlock.CMsgHeroBuildR\theroBuild\"\xc3\x01\n" +
	"\"CCitadelClientMsg_HideoutMenuState\x12^\n" +
	"\n" +
	"menu_state\x18\x01 \x01(\x0e26.deadlock.CCitadelClientMsg_HideoutMenuState.MenuState:\ak_eNoneR\tmenuState\"=\n" +
	"\tMenuState\x12\v\n" +
	"\ak_eNone\x10\x00\x12\x11\n" +
	"\rk_eEscapeMenu\x10\x01\x12\x10\n" +
	"\fk_eDashboard\x10\x02\"X\n" +
	"\x1eCCitadelClientMsg_HideoutSpawn\x12\x17\n" +
	"\ahero_id\x18\x01 \x01(\rR\x06heroId\x12\x1d\n" +
	"\n" +
	"show_intro\x18\x02 \x01(\bR\tshowIntro\"R\n" +
	")CCitadelClientMsg_HideoutMatchmakingState\x12%\n" +
	"\x0eis_matchmaking\x18\x01 \x01(\bR\risMatchmaking\"&\n" +
	"$CCitadelClientMsg_PlayerStatsUpdated\"`\n" +
	"4CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus\x12(\n" +
	"\x10votes_cast_total\x18\x01 \x01(\rR\x0evotesCastTotal*\xa7\x05\n" +
	"\x16ECitadelClientMessages\x12\x17\n" +
	"\x12CITADEL_CM_MapPing\x10\xea\a\x12 \n" +
	"\x1bCITADEL_CM_PerformanceStats\x10\xeb\a\x12\x19\n" +
	"\x14CITADEL_CM_PingWheel\x10\xec\a\x12\x17\n" +
	"\x12CITADEL_CM_ChatMsg\x10\xed\a\x12\x1a\n" +
	"\x15CITADEL_CM_PerfReport\x10\xee\a\x12\x1d\n" +
	"\x18CITADEL_CM_QuickResponse\x10\xef\a\x12\x15\n" +
	"\x10CITADEL_CM_Pause\x10\xf0\a\x12\x17\n" +
	"\x12CITADEL_CM_MapLine\x10\xf1\a\x12\x1b\n" +
	"\x16CITADEL_CM_AbilityPing\x10\xf2\a\x12%\n" +
	" CITADEL_CM_ExecuteMapUnitAbility\x10\xf3\a\x12\x1e\n" +
	"\x19CITADEL_CM_GetDamageStats\x10\xf4\a\x12\x1b\n" +
	"\x16CITADEL_CM_CheaterVote\x10\xf5\a\x12\x1b\n" +
	"\x16CITADEL_CM_MutePlayers\x10\xf6\a\x12\x1b\n" +
	"\x16CITADEL_CM_HitMismatch\x10\xf7\a\x12\x1c\n" +
	"\x17CITADEL_CM_HideoutStart\x10\xf8\a\x12\x19\n" +
	"\x14CITADEL_CM_HeroBuild\x10\xf9\a\x12 \n" +
	"\x1bCITADEL_CM_HideoutMenuState\x10\xfa\a\x12\x1c\n" +
	"\x17CITADEL_CM_HideoutSpawn\x10\xfb\a\x12'\n" +
	"\"CITADEL_CM_HideoutMatchmakingState\x10\xfc\a\x12\"\n" +
	"\x1dCITADEL_CM_PlayerStatsUpdated\x10\xfd\a\x122\n" +
	"-CITADEL_CM_HideoutUpdateHeroReleaseVoteStatus\x10\xfe\aB4Z2github.com/RyPort/paradox-parser/deadlock;deadlock"

var (
	file_citadel_clientmessages_proto_rawDescOnce sync.Once
	file_citadel_clientmessages_proto_rawDescData []byte
)

func file_citadel_clientmessages_proto_rawDescGZIP() []byte {
	file_citadel_clientmessages_proto_rawDescOnce.Do(func() {
		file_citadel_clientmessages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_citadel_clientmessages_proto_rawDesc), len(file_citadel_clientmessages_proto_rawDesc)))
	})
	return file_citadel_clientmessages_proto_rawDescData
}

var file_citadel_clientmessages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_citadel_clientmessages_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_citadel_clientmessages_proto_goTypes = []any{
	(ECitadelClientMessages)(0),                                  // 0: deadlock.ECitadelClientMessages
	(CCitadelClientMsg_HideoutMenuState_MenuState)(0),            // 1: deadlock.CCitadelClientMsg_HideoutMenuState.MenuState
	(*CCitadelClientMsg_Pause)(nil),                              // 2: deadlock.CCitadelClientMsg_Pause
	(*CCitadelClientMsg_MapPing)(nil),                            // 3: deadlock.CCitadelClientMsg_MapPing
	(*CCitadelClientMsg_PingWheel)(nil),                          // 4: deadlock.CCitadelClientMsg_PingWheel
	(*CCitadelClientMsg_AbilityPing)(nil),                        // 5: deadlock.CCitadelClientMsg_AbilityPing
	(*CCitadelClientMsg_MapLine)(nil),                            // 6: deadlock.CCitadelClientMsg_MapLine
	(*CCitadelClientMsg_QuickResponse)(nil),                      // 7: deadlock.CCitadelClientMsg_QuickResponse
	(*CCitadelClientMsg_PerformanceStats)(nil),                   // 8: deadlock.CCitadelClientMsg_PerformanceStats
	(*CCitadelClientMsg_ChatMsg)(nil),                            // 9: deadlock.CCitadelClientMsg_ChatMsg
	(*CCitadelClientMsg_PerfReport)(nil),                         // 10: deadlock.CCitadelClientMsg_PerfReport
	(*CCitadelClientMsg_GetDamageStats)(nil),                     // 11: deadlock.CCitadelClientMsg_GetDamageStats
	(*CCitadelClientCachedPlayerStats)(nil),                      // 12: deadlock.CCitadelClientCachedPlayerStats
	(*CCitadelClientMsg_ExecuteMapUnitAbility)(nil),              // 13: deadlock.CCitadelClientMsg_ExecuteMapUnitAbility
	(*CCitadelClientMsg_CheaterVote)(nil),                        // 14: deadlock.CCitadelClientMsg_CheaterVote
	(*CCitadelClientMsg_MutePlayers)(nil),                        // 15: deadlock.CCitadelClientMsg_MutePlayers
	(*CCitadelClientMsg_HitMismatch)(nil),                        // 16: deadlock.CCitadelClientMsg_HitMismatch
	(*CCitadelClientMsg_HideoutStart)(nil),                       // 17: deadlock.CCitadelClientMsg_HideoutStart
	(*CCitadelClientMsg_HeroBuild)(nil),                          // 18: deadlock.CCitadelClientMsg_HeroBuild
	(*CCitadelClientMsg_HideoutMenuState)(nil),                   // 19: deadlock.CCitadelClientMsg_HideoutMenuState
	(*CCitadelClientMsg_HideoutSpawn)(nil),                       // 20: deadlock.CCitadelClientMsg_HideoutSpawn
	(*CCitadelClientMsg_HideoutMatchmakingState)(nil),            // 21: deadlock.CCitadelClientMsg_HideoutMatchmakingState
	(*CCitadelClientMsg_PlayerStatsUpdated)(nil),                 // 22: deadlock.CCitadelClientMsg_PlayerStatsUpdated
	(*CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus)(nil), // 23: deadlock.CCitadelClientMsg_HideoutUpdateHeroReleaseVoteStatus
	(*CCitadelClientCachedPlayerStats_Stat)(nil),                 // 24: deadlock.CCitadelClientCachedPlayerStats.Stat
	(*CMsgVector)(nil),                                           // 25: deadlock.CMsgVector
	(*CMsgMapLine)(nil),                                          // 26: deadlock.CMsgMapLine
	(CMsgLaneColor)(0),                                           // 27: deadlock.CMsgLaneColor
	(*CMsgHeroBuild)(nil),                                        // 28: deadlock.CMsgHeroBuild
}
var file_citadel_clientmessages_proto_depIdxs = []int32{
	25, // 0: deadlock.CCitadelClientMsg_MapPing.ping_location:type_name -> deadlock.CMsgVector
	25, // 1: deadlock.CCitadelClientMsg_PingWheel.ping_location:type_name -> deadlock.CMsgVector
	26, // 2: deadlock.CCitadelClientMsg_MapLine.mapline:type_name -> deadlock.CMsgMapLine
	27, // 3: deadlock.CCitadelClientMsg_ChatMsg.lane_color:type_name -> deadlock.CMsgLaneColor
	24, // 4: deadlock.CCitadelClientCachedPlayerStats.stats:type_name -> deadlock.CCitadelClientCachedPlayerStats.Stat
	28, // 5: deadlock.CCitadelClientMsg_HeroBuild.hero_build:type_name -> deadlock.CMsgHeroBuild
	1,  // 6: deadlock.CCitadelClientMsg_HideoutMenuState.menu_state:type_name -> deadlock.CCitadelClientMsg_HideoutMenuState.MenuState
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_citadel_clientmessages_proto_init() }
func file_citadel_clientmessages_proto_init() {
	if File_citadel_clientmessages_proto != nil {
		return
	}
	file_networkbasetypes_proto_init()
	file_citadel_gcmessages_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_citadel_clientmessages_proto_rawDesc), len(file_citadel_clientmessages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_citadel_clientmessages_proto_goTypes,
		DependencyIndexes: file_citadel_clientmessages_proto_depIdxs,
		EnumInfos:         file_citadel_clientmessages_proto_enumTypes,
		MessageInfos:      file_citadel_clientmessages_proto_msgTypes,
	}.Build()
	File_citadel_clientmessages_proto = out.File
	file_citadel_clientmessages_proto_goTypes = nil
	file_citadel_clientmessages_proto_depIdxs = nil
}
