// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.6.1
// source: citadel_gamemessages.proto

package deadlock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ECitadelGameMessages int32

const (
	ECitadelGameMessages_k_EMsgGameServerToClientConnectionStatus ECitadelGameMessages = 10
	ECitadelGameMessages_k_EMsgGameServerToClientInitialGameState ECitadelGameMessages = 12
	ECitadelGameMessages_k_EMsgGameServerToClientGameCompleted    ECitadelGameMessages = 13
	ECitadelGameMessages_k_EMsgGameServerToClientGoodbye          ECitadelGameMessages = 15
)

// Enum value maps for ECitadelGameMessages.
var (
	ECitadelGameMessages_name = map[int32]string{
		10: "k_EMsgGameServerToClientConnectionStatus",
		12: "k_EMsgGameServerToClientInitialGameState",
		13: "k_EMsgGameServerToClientGameCompleted",
		15: "k_EMsgGameServerToClientGoodbye",
	}
	ECitadelGameMessages_value = map[string]int32{
		"k_EMsgGameServerToClientConnectionStatus": 10,
		"k_EMsgGameServerToClientInitialGameState": 12,
		"k_EMsgGameServerToClientGameCompleted":    13,
		"k_EMsgGameServerToClientGoodbye":          15,
	}
)

func (x ECitadelGameMessages) Enum() *ECitadelGameMessages {
	p := new(ECitadelGameMessages)
	*p = x
	return p
}

func (x ECitadelGameMessages) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECitadelGameMessages) Descriptor() protoreflect.EnumDescriptor {
	return file_citadel_gamemessages_proto_enumTypes[0].Descriptor()
}

func (ECitadelGameMessages) Type() protoreflect.EnumType {
	return &file_citadel_gamemessages_proto_enumTypes[0]
}

func (x ECitadelGameMessages) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ECitadelGameMessages) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ECitadelGameMessages(num)
	return nil
}

// Deprecated: Use ECitadelGameMessages.Descriptor instead.
func (ECitadelGameMessages) EnumDescriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{0}
}

type ECitadelDisconnectReason int32

const (
	ECitadelDisconnectReason_k_ECitadelDisconnectReason_UserLeaveMatch            ECitadelDisconnectReason = 1001
	ECitadelDisconnectReason_k_ECitadelDisconnectReason_UserQuitApp               ECitadelDisconnectReason = 1002
	ECitadelDisconnectReason_k_ECitadelDisconnectReason_UserCancel                ECitadelDisconnectReason = 1003
	ECitadelDisconnectReason_k_ECitadelDisconnectReason_Goodbye                   ECitadelDisconnectReason = 1004
	ECitadelDisconnectReason_k_ECitadelDisconnectReason_BadMessage                ECitadelDisconnectReason = 2001
	ECitadelDisconnectReason_k_ECitadelDisconnectReason_GameDestroyedUnexpectedly ECitadelDisconnectReason = 2002
	ECitadelDisconnectReason_k_ECitadelDisconnectReason_ChangingServer            ECitadelDisconnectReason = 2003
	ECitadelDisconnectReason_k_ECitadelDisconnectReason_OldConnection             ECitadelDisconnectReason = 2004
	ECitadelDisconnectReason_k_ECitadelDisconnectReason_GoodbyeUnrecognizedGame   ECitadelDisconnectReason = 2005
)

// Enum value maps for ECitadelDisconnectReason.
var (
	ECitadelDisconnectReason_name = map[int32]string{
		1001: "k_ECitadelDisconnectReason_UserLeaveMatch",
		1002: "k_ECitadelDisconnectReason_UserQuitApp",
		1003: "k_ECitadelDisconnectReason_UserCancel",
		1004: "k_ECitadelDisconnectReason_Goodbye",
		2001: "k_ECitadelDisconnectReason_BadMessage",
		2002: "k_ECitadelDisconnectReason_GameDestroyedUnexpectedly",
		2003: "k_ECitadelDisconnectReason_ChangingServer",
		2004: "k_ECitadelDisconnectReason_OldConnection",
		2005: "k_ECitadelDisconnectReason_GoodbyeUnrecognizedGame",
	}
	ECitadelDisconnectReason_value = map[string]int32{
		"k_ECitadelDisconnectReason_UserLeaveMatch":            1001,
		"k_ECitadelDisconnectReason_UserQuitApp":               1002,
		"k_ECitadelDisconnectReason_UserCancel":                1003,
		"k_ECitadelDisconnectReason_Goodbye":                   1004,
		"k_ECitadelDisconnectReason_BadMessage":                2001,
		"k_ECitadelDisconnectReason_GameDestroyedUnexpectedly": 2002,
		"k_ECitadelDisconnectReason_ChangingServer":            2003,
		"k_ECitadelDisconnectReason_OldConnection":             2004,
		"k_ECitadelDisconnectReason_GoodbyeUnrecognizedGame":   2005,
	}
)

func (x ECitadelDisconnectReason) Enum() *ECitadelDisconnectReason {
	p := new(ECitadelDisconnectReason)
	*p = x
	return p
}

func (x ECitadelDisconnectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECitadelDisconnectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_citadel_gamemessages_proto_enumTypes[1].Descriptor()
}

func (ECitadelDisconnectReason) Type() protoreflect.EnumType {
	return &file_citadel_gamemessages_proto_enumTypes[1]
}

func (x ECitadelDisconnectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ECitadelDisconnectReason) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ECitadelDisconnectReason(num)
	return nil
}

// Deprecated: Use ECitadelDisconnectReason.Descriptor instead.
func (ECitadelDisconnectReason) EnumDescriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{1}
}

type CMsgGameServerToClientConnectionStatus_EStatus int32

const (
	CMsgGameServerToClientConnectionStatus_k_EConnected    CMsgGameServerToClientConnectionStatus_EStatus = 1
	CMsgGameServerToClientConnectionStatus_k_EDisconnected CMsgGameServerToClientConnectionStatus_EStatus = 2
)

// Enum value maps for CMsgGameServerToClientConnectionStatus_EStatus.
var (
	CMsgGameServerToClientConnectionStatus_EStatus_name = map[int32]string{
		1: "k_EConnected",
		2: "k_EDisconnected",
	}
	CMsgGameServerToClientConnectionStatus_EStatus_value = map[string]int32{
		"k_EConnected":    1,
		"k_EDisconnected": 2,
	}
)

func (x CMsgGameServerToClientConnectionStatus_EStatus) Enum() *CMsgGameServerToClientConnectionStatus_EStatus {
	p := new(CMsgGameServerToClientConnectionStatus_EStatus)
	*p = x
	return p
}

func (x CMsgGameServerToClientConnectionStatus_EStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMsgGameServerToClientConnectionStatus_EStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_citadel_gamemessages_proto_enumTypes[2].Descriptor()
}

func (CMsgGameServerToClientConnectionStatus_EStatus) Type() protoreflect.EnumType {
	return &file_citadel_gamemessages_proto_enumTypes[2]
}

func (x CMsgGameServerToClientConnectionStatus_EStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CMsgGameServerToClientConnectionStatus_EStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CMsgGameServerToClientConnectionStatus_EStatus(num)
	return nil
}

// Deprecated: Use CMsgGameServerToClientConnectionStatus_EStatus.Descriptor instead.
func (CMsgGameServerToClientConnectionStatus_EStatus) EnumDescriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{3, 0}
}

type CMsgClientServerHeader struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GameInstanceId   *uint64                `protobuf:"varint,1,opt,name=game_instance_id,json=gameInstanceId" json:"game_instance_id,omitempty"`
	LocalPlayerIndex *uint32                `protobuf:"varint,2,opt,name=local_player_index,json=localPlayerIndex" json:"local_player_index,omitempty"`
	Payload          []byte                 `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	MsgId            *ECitadelGameMessages  `protobuf:"varint,4,opt,name=msg_id,json=msgId,enum=deadlock.ECitadelGameMessages,def=10" json:"msg_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for CMsgClientServerHeader fields.
const (
	Default_CMsgClientServerHeader_MsgId = ECitadelGameMessages_k_EMsgGameServerToClientConnectionStatus
)

func (x *CMsgClientServerHeader) Reset() {
	*x = CMsgClientServerHeader{}
	mi := &file_citadel_gamemessages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientServerHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientServerHeader) ProtoMessage() {}

func (x *CMsgClientServerHeader) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gamemessages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientServerHeader.ProtoReflect.Descriptor instead.
func (*CMsgClientServerHeader) Descriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgClientServerHeader) GetGameInstanceId() uint64 {
	if x != nil && x.GameInstanceId != nil {
		return *x.GameInstanceId
	}
	return 0
}

func (x *CMsgClientServerHeader) GetLocalPlayerIndex() uint32 {
	if x != nil && x.LocalPlayerIndex != nil {
		return *x.LocalPlayerIndex
	}
	return 0
}

func (x *CMsgClientServerHeader) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CMsgClientServerHeader) GetMsgId() ECitadelGameMessages {
	if x != nil && x.MsgId != nil {
		return *x.MsgId
	}
	return Default_CMsgClientServerHeader_MsgId
}

type CMsgGameServerToClientGameCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgGameServerToClientGameCompleted) Reset() {
	*x = CMsgGameServerToClientGameCompleted{}
	mi := &file_citadel_gamemessages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGameServerToClientGameCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGameServerToClientGameCompleted) ProtoMessage() {}

func (x *CMsgGameServerToClientGameCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gamemessages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGameServerToClientGameCompleted.ProtoReflect.Descriptor instead.
func (*CMsgGameServerToClientGameCompleted) Descriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{1}
}

type CMsgGameServerToClientGoodbye struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgGameServerToClientGoodbye) Reset() {
	*x = CMsgGameServerToClientGoodbye{}
	mi := &file_citadel_gamemessages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGameServerToClientGoodbye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGameServerToClientGoodbye) ProtoMessage() {}

func (x *CMsgGameServerToClientGoodbye) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gamemessages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGameServerToClientGoodbye.ProtoReflect.Descriptor instead.
func (*CMsgGameServerToClientGoodbye) Descriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{2}
}

type CMsgGameServerToClientConnectionStatus struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Players       []*CMsgGameServerToClientConnectionStatus_Player `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgGameServerToClientConnectionStatus) Reset() {
	*x = CMsgGameServerToClientConnectionStatus{}
	mi := &file_citadel_gamemessages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGameServerToClientConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGameServerToClientConnectionStatus) ProtoMessage() {}

func (x *CMsgGameServerToClientConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gamemessages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGameServerToClientConnectionStatus.ProtoReflect.Descriptor instead.
func (*CMsgGameServerToClientConnectionStatus) Descriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgGameServerToClientConnectionStatus) GetPlayers() []*CMsgGameServerToClientConnectionStatus_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type CClientReconnectInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServerSteamId        *uint64                `protobuf:"fixed64,1,opt,name=server_steam_id,json=serverSteamId" json:"server_steam_id,omitempty"`
	LobbyId              *uint64                `protobuf:"varint,2,opt,name=lobby_id,json=lobbyId" json:"lobby_id,omitempty"`
	TimeUpdated          *uint32                `protobuf:"varint,3,opt,name=time_updated,json=timeUpdated" json:"time_updated,omitempty"`
	UdpConnectIp         *uint32                `protobuf:"varint,4,opt,name=udp_connect_ip,json=udpConnectIp" json:"udp_connect_ip,omitempty"`
	UdpConnectPort       *uint32                `protobuf:"varint,5,opt,name=udp_connect_port,json=udpConnectPort" json:"udp_connect_port,omitempty"`
	CompatibilityVersion *uint32                `protobuf:"varint,6,opt,name=compatibility_version,json=compatibilityVersion" json:"compatibility_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CClientReconnectInfo) Reset() {
	*x = CClientReconnectInfo{}
	mi := &file_citadel_gamemessages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CClientReconnectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CClientReconnectInfo) ProtoMessage() {}

func (x *CClientReconnectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gamemessages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CClientReconnectInfo.ProtoReflect.Descriptor instead.
func (*CClientReconnectInfo) Descriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{4}
}

func (x *CClientReconnectInfo) GetServerSteamId() uint64 {
	if x != nil && x.ServerSteamId != nil {
		return *x.ServerSteamId
	}
	return 0
}

func (x *CClientReconnectInfo) GetLobbyId() uint64 {
	if x != nil && x.LobbyId != nil {
		return *x.LobbyId
	}
	return 0
}

func (x *CClientReconnectInfo) GetTimeUpdated() uint32 {
	if x != nil && x.TimeUpdated != nil {
		return *x.TimeUpdated
	}
	return 0
}

func (x *CClientReconnectInfo) GetUdpConnectIp() uint32 {
	if x != nil && x.UdpConnectIp != nil {
		return *x.UdpConnectIp
	}
	return 0
}

func (x *CClientReconnectInfo) GetUdpConnectPort() uint32 {
	if x != nil && x.UdpConnectPort != nil {
		return *x.UdpConnectPort
	}
	return 0
}

func (x *CClientReconnectInfo) GetCompatibilityVersion() uint32 {
	if x != nil && x.CompatibilityVersion != nil {
		return *x.CompatibilityVersion
	}
	return 0
}

type CMsgClientAccountSyncStorageFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *uint32                `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Ids           []uint32               `protobuf:"varint,2,rep,name=ids" json:"ids,omitempty"`
	Values        []uint32               `protobuf:"varint,3,rep,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientAccountSyncStorageFile) Reset() {
	*x = CMsgClientAccountSyncStorageFile{}
	mi := &file_citadel_gamemessages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientAccountSyncStorageFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientAccountSyncStorageFile) ProtoMessage() {}

func (x *CMsgClientAccountSyncStorageFile) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gamemessages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientAccountSyncStorageFile.ProtoReflect.Descriptor instead.
func (*CMsgClientAccountSyncStorageFile) Descriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{5}
}

func (x *CMsgClientAccountSyncStorageFile) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *CMsgClientAccountSyncStorageFile) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *CMsgClientAccountSyncStorageFile) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type CMsgGameServerToClientConnectionStatus_Player struct {
	state                     protoimpl.MessageState                          `protogen:"open.v1"`
	PlayerSlot                *int32                                          `protobuf:"varint,1,opt,name=player_slot,json=playerSlot,def=-1" json:"player_slot,omitempty"`
	Status                    *CMsgGameServerToClientConnectionStatus_EStatus `protobuf:"varint,2,opt,name=status,enum=deadlock.CMsgGameServerToClientConnectionStatus_EStatus,def=1" json:"status,omitempty"`
	InactivityTicking         *bool                                           `protobuf:"varint,3,opt,name=inactivity_ticking,json=inactivityTicking" json:"inactivity_ticking,omitempty"`
	InactivityMsRemaining     *uint32                                         `protobuf:"varint,4,opt,name=inactivity_ms_remaining,json=inactivityMsRemaining" json:"inactivity_ms_remaining,omitempty"`
	InactivityAnimMsRemaining *uint32                                         `protobuf:"varint,5,opt,name=inactivity_anim_ms_remaining,json=inactivityAnimMsRemaining" json:"inactivity_anim_ms_remaining,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

// Default values for CMsgGameServerToClientConnectionStatus_Player fields.
const (
	Default_CMsgGameServerToClientConnectionStatus_Player_PlayerSlot = int32(-1)
	Default_CMsgGameServerToClientConnectionStatus_Player_Status     = CMsgGameServerToClientConnectionStatus_k_EConnected
)

func (x *CMsgGameServerToClientConnectionStatus_Player) Reset() {
	*x = CMsgGameServerToClientConnectionStatus_Player{}
	mi := &file_citadel_gamemessages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGameServerToClientConnectionStatus_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGameServerToClientConnectionStatus_Player) ProtoMessage() {}

func (x *CMsgGameServerToClientConnectionStatus_Player) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_gamemessages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGameServerToClientConnectionStatus_Player.ProtoReflect.Descriptor instead.
func (*CMsgGameServerToClientConnectionStatus_Player) Descriptor() ([]byte, []int) {
	return file_citadel_gamemessages_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CMsgGameServerToClientConnectionStatus_Player) GetPlayerSlot() int32 {
	if x != nil && x.PlayerSlot != nil {
		return *x.PlayerSlot
	}
	return Default_CMsgGameServerToClientConnectionStatus_Player_PlayerSlot
}

func (x *CMsgGameServerToClientConnectionStatus_Player) GetStatus() CMsgGameServerToClientConnectionStatus_EStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Default_CMsgGameServerToClientConnectionStatus_Player_Status
}

func (x *CMsgGameServerToClientConnectionStatus_Player) GetInactivityTicking() bool {
	if x != nil && x.InactivityTicking != nil {
		return *x.InactivityTicking
	}
	return false
}

func (x *CMsgGameServerToClientConnectionStatus_Player) GetInactivityMsRemaining() uint32 {
	if x != nil && x.InactivityMsRemaining != nil {
		return *x.InactivityMsRemaining
	}
	return 0
}

func (x *CMsgGameServerToClientConnectionStatus_Player) GetInactivityAnimMsRemaining() uint32 {
	if x != nil && x.InactivityAnimMsRemaining != nil {
		return *x.InactivityAnimMsRemaining
	}
	return 0
}

var File_citadel_gamemessages_proto protoreflect.FileDescriptor

const file_citadel_gamemessages_proto_rawDesc = "" +
	"\n" +
	"\x1acitadel_gamemessages.proto\x12\bdeadlock\x1a\x1fcitadel_gcmessages_common.proto\"\xeb\x01\n" +
	"\x16CMsgClientServerHeader\x12(\n" +
	"\x10game_instance_id\x18\x01 \x01(\x04R\x0egameInstanceId\x12,\n" +
	"\x12local_player_index\x18\x02 \x01(\rR\x10localPlayerIndex\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12_\n" +
	"\x06msg_id\x18\x04 \x01(\x0e2\x1e.deadlock.ECitadelGameMessages:(k_EMsgGameServerToClientConnectionStatusR\x05msgId\"%\n" +
	"#CMsgGameServerToClientGameCompleted\"\x1f\n" +
	"\x1dCMsgGameServerToClientGoodbye\"\xe5\x03\n" +
	"&CMsgGameServerToClientConnectionStatus\x12Q\n" +
	"\aplayers\x18\x01 \x03(\v27.deadlock.CMsgGameServerToClientConnectionStatus.PlayerR\aplayers\x1a\xb5\x02\n" +
	"\x06Player\x12#\n" +
	"\vplayer_slot\x18\x01 \x01(\x05:\x02-1R\n" +
	"playerSlot\x12^\n" +
	"\x06status\x18\x02 \x01(\x0e28.deadlock.CMsgGameServerToClientConnectionStatus.EStatus:\fk_EConnectedR\x06status\x12-\n" +
	"\x12inactivity_ticking\x18\x03 \x01(\bR\x11inactivityTicking\x126\n" +
	"\x17inactivity_ms_remaining\x18\x04 \x01(\rR\x15inactivityMsRemaining\x12?\n" +
	"\x1cinactivity_anim_ms_remaining\x18\x05 \x01(\rR\x19inactivityAnimMsRemaining\"0\n" +
	"\aEStatus\x12\x10\n" +
	"\fk_EConnected\x10\x01\x12\x13\n" +
	"\x0fk_EDisconnected\x10\x02\"\x81\x02\n" +
	"\x14CClientReconnectInfo\x12&\n" +
	"\x0fserver_steam_id\x18\x01 \x01(\x06R\rserverSteamId\x12\x19\n" +
	"\blobby_id\x18\x02 \x01(\x04R\alobbyId\x12!\n" +
	"\ftime_updated\x18\x03 \x01(\rR\vtimeUpdated\x12$\n" +
	"\x0eudp_connect_ip\x18\x04 \x01(\rR\fudpConnectIp\x12(\n" +
	"\x10udp_connect_port\x18\x05 \x01(\rR\x0eudpConnectPort\x123\n" +
	"\x15compatibility_version\x18\x06 \x01(\rR\x14compatibilityVersion\"f\n" +
	" CMsgClientAccountSyncStorageFile\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\rR\x03ids\x12\x16\n" +
	"\x06values\x18\x03 \x03(\rR\x06values*\xc2\x01\n" +
	"\x14ECitadelGameMessages\x12,\n" +
	"(k_EMsgGameServerToClientConnectionStatus\x10\n" +
	"\x12,\n" +
	"(k_EMsgGameServerToClientInitialGameState\x10\f\x12)\n" +
	"%k_EMsgGameServerToClientGameCompleted\x10\r\x12#\n" +
	"\x1fk_EMsgGameServerToClientGoodbye\x10\x0f*\xcb\x03\n" +
	"\x18ECitadelDisconnectReason\x12.\n" +
	")k_ECitadelDisconnectReason_UserLeaveMatch\x10\xe9\a\x12+\n" +
	"&k_ECitadelDisconnectReason_UserQuitApp\x10\xea\a\x12*\n" +
	"%k_ECitadelDisconnectReason_UserCancel\x10\xeb\a\x12'\n" +
	"\"k_ECitadelDisconnectReason_Goodbye\x10\xec\a\x12*\n" +
	"%k_ECitadelDisconnectReason_BadMessage\x10\xd1\x0f\x129\n" +
	"4k_ECitadelDisconnectReason_GameDestroyedUnexpectedly\x10\xd2\x0f\x12.\n" +
	")k_ECitadelDisconnectReason_ChangingServer\x10\xd3\x0f\x12-\n" +
	"(k_ECitadelDisconnectReason_OldConnection\x10\xd4\x0f\x127\n" +
	"2k_ECitadelDisconnectReason_GoodbyeUnrecognizedGame\x10\xd5\x0fB4Z2github.com/RyPort/paradox-parser/deadlock;deadlock"

var (
	file_citadel_gamemessages_proto_rawDescOnce sync.Once
	file_citadel_gamemessages_proto_rawDescData []byte
)

func file_citadel_gamemessages_proto_rawDescGZIP() []byte {
	file_citadel_gamemessages_proto_rawDescOnce.Do(func() {
		file_citadel_gamemessages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_citadel_gamemessages_proto_rawDesc), len(file_citadel_gamemessages_proto_rawDesc)))
	})
	return file_citadel_gamemessages_proto_rawDescData
}

var file_citadel_gamemessages_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_citadel_gamemessages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_citadel_gamemessages_proto_goTypes = []any{
	(ECitadelGameMessages)(0),                             // 0: deadlock.ECitadelGameMessages
	(ECitadelDisconnectReason)(0),                         // 1: deadlock.ECitadelDisconnectReason
	(CMsgGameServerToClientConnectionStatus_EStatus)(0),   // 2: deadlock.CMsgGameServerToClientConnectionStatus.EStatus
	(*CMsgClientServerHeader)(nil),                        // 3: deadlock.CMsgClientServerHeader
	(*CMsgGameServerToClientGameCompleted)(nil),           // 4: deadlock.CMsgGameServerToClientGameCompleted
	(*CMsgGameServerToClientGoodbye)(nil),                 // 5: deadlock.CMsgGameServerToClientGoodbye
	(*CMsgGameServerToClientConnectionStatus)(nil),        // 6: deadlock.CMsgGameServerToClientConnectionStatus
	(*CClientReconnectInfo)(nil),                          // 7: deadlock.CClientReconnectInfo
	(*CMsgClientAccountSyncStorageFile)(nil),              // 8: deadlock.CMsgClientAccountSyncStorageFile
	(*CMsgGameServerToClientConnectionStatus_Player)(nil), // 9: deadlock.CMsgGameServerToClientConnectionStatus.Player
}
var file_citadel_gamemessages_proto_depIdxs = []int32{
	0, // 0: deadlock.CMsgClientServerHeader.msg_id:type_name -> deadlock.ECitadelGameMessages
	9, // 1: deadlock.CMsgGameServerToClientConnectionStatus.players:type_name -> deadlock.CMsgGameServerToClientConnectionStatus.Player
	2, // 2: deadlock.CMsgGameServerToClientConnectionStatus.Player.status:type_name -> deadlock.CMsgGameServerToClientConnectionStatus.EStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_citadel_gamemessages_proto_init() }
func file_citadel_gamemessages_proto_init() {
	if File_citadel_gamemessages_proto != nil {
		return
	}
	file_citadel_gcmessages_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_citadel_gamemessages_proto_rawDesc), len(file_citadel_gamemessages_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_citadel_gamemessages_proto_goTypes,
		DependencyIndexes: file_citadel_gamemessages_proto_depIdxs,
		EnumInfos:         file_citadel_gamemessages_proto_enumTypes,
		MessageInfos:      file_citadel_gamemessages_proto_msgTypes,
	}.Build()
	File_citadel_gamemessages_proto = out.File
	file_citadel_gamemessages_proto_goTypes = nil
	file_citadel_gamemessages_proto_depIdxs = nil
}
