// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.6.1
// source: citadel_usercmd.proto

package deadlock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CCitadelUserCmdPB struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Base                  *CBaseUserCmdPB        `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	VecCameraPosition     *CMsgVector            `protobuf:"bytes,2,opt,name=vec_camera_position,json=vecCameraPosition" json:"vec_camera_position,omitempty"`
	AngCameraAngles       *CMsgQAngle            `protobuf:"bytes,3,opt,name=ang_camera_angles,json=angCameraAngles" json:"ang_camera_angles,omitempty"`
	ExecuteAbilityIndices *int32                 `protobuf:"varint,4,opt,name=execute_ability_indices,json=executeAbilityIndices" json:"execute_ability_indices,omitempty"`
	InShop                *bool                  `protobuf:"varint,5,opt,name=in_shop,json=inShop" json:"in_shop,omitempty"`
	CameraRoamingSpeed    *float32               `protobuf:"fixed32,6,opt,name=camera_roaming_speed,json=cameraRoamingSpeed" json:"camera_roaming_speed,omitempty"`
	UsingFreeCursor       *bool                  `protobuf:"varint,8,opt,name=using_free_cursor,json=usingFreeCursor" json:"using_free_cursor,omitempty"`
	EnemyHeroAimedAt      *int32                 `protobuf:"varint,10,opt,name=enemy_hero_aimed_at,json=enemyHeroAimedAt,def=-1" json:"enemy_hero_aimed_at,omitempty"`
	ViewDeltaX            []int32                `protobuf:"varint,11,rep,name=view_delta_x,json=viewDeltaX" json:"view_delta_x,omitempty"`
	ViewDeltaY            []int32                `protobuf:"varint,12,rep,name=view_delta_y,json=viewDeltaY" json:"view_delta_y,omitempty"`
	IsInThirdPersonView   *bool                  `protobuf:"varint,13,opt,name=is_in_third_person_view,json=isInThirdPersonView" json:"is_in_third_person_view,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

// Default values for CCitadelUserCmdPB fields.
const (
	Default_CCitadelUserCmdPB_EnemyHeroAimedAt = int32(-1)
)

func (x *CCitadelUserCmdPB) Reset() {
	*x = CCitadelUserCmdPB{}
	mi := &file_citadel_usercmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCitadelUserCmdPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCitadelUserCmdPB) ProtoMessage() {}

func (x *CCitadelUserCmdPB) ProtoReflect() protoreflect.Message {
	mi := &file_citadel_usercmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCitadelUserCmdPB.ProtoReflect.Descriptor instead.
func (*CCitadelUserCmdPB) Descriptor() ([]byte, []int) {
	return file_citadel_usercmd_proto_rawDescGZIP(), []int{0}
}

func (x *CCitadelUserCmdPB) GetBase() *CBaseUserCmdPB {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CCitadelUserCmdPB) GetVecCameraPosition() *CMsgVector {
	if x != nil {
		return x.VecCameraPosition
	}
	return nil
}

func (x *CCitadelUserCmdPB) GetAngCameraAngles() *CMsgQAngle {
	if x != nil {
		return x.AngCameraAngles
	}
	return nil
}

func (x *CCitadelUserCmdPB) GetExecuteAbilityIndices() int32 {
	if x != nil && x.ExecuteAbilityIndices != nil {
		return *x.ExecuteAbilityIndices
	}
	return 0
}

func (x *CCitadelUserCmdPB) GetInShop() bool {
	if x != nil && x.InShop != nil {
		return *x.InShop
	}
	return false
}

func (x *CCitadelUserCmdPB) GetCameraRoamingSpeed() float32 {
	if x != nil && x.CameraRoamingSpeed != nil {
		return *x.CameraRoamingSpeed
	}
	return 0
}

func (x *CCitadelUserCmdPB) GetUsingFreeCursor() bool {
	if x != nil && x.UsingFreeCursor != nil {
		return *x.UsingFreeCursor
	}
	return false
}

func (x *CCitadelUserCmdPB) GetEnemyHeroAimedAt() int32 {
	if x != nil && x.EnemyHeroAimedAt != nil {
		return *x.EnemyHeroAimedAt
	}
	return Default_CCitadelUserCmdPB_EnemyHeroAimedAt
}

func (x *CCitadelUserCmdPB) GetViewDeltaX() []int32 {
	if x != nil {
		return x.ViewDeltaX
	}
	return nil
}

func (x *CCitadelUserCmdPB) GetViewDeltaY() []int32 {
	if x != nil {
		return x.ViewDeltaY
	}
	return nil
}

func (x *CCitadelUserCmdPB) GetIsInThirdPersonView() bool {
	if x != nil && x.IsInThirdPersonView != nil {
		return *x.IsInThirdPersonView
	}
	return false
}

var File_citadel_usercmd_proto protoreflect.FileDescriptor

const file_citadel_usercmd_proto_rawDesc = "" +
	"\n" +
	"\x15citadel_usercmd.proto\x12\bdeadlock\x1a\x16networkbasetypes.proto\x1a\rusercmd.proto\"\xa5\x04\n" +
	"\x11CCitadelUserCmdPB\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.deadlock.CBaseUserCmdPBR\x04base\x12D\n" +
	"\x13vec_camera_position\x18\x02 \x01(\v2\x14.deadlock.CMsgVectorR\x11vecCameraPosition\x12@\n" +
	"\x11ang_camera_angles\x18\x03 \x01(\v2\x14.deadlock.CMsgQAngleR\x0fangCameraAngles\x126\n" +
	"\x17execute_ability_indices\x18\x04 \x01(\x05R\x15executeAbilityIndices\x12\x17\n" +
	"\ain_shop\x18\x05 \x01(\bR\x06inShop\x120\n" +
	"\x14camera_roaming_speed\x18\x06 \x01(\x02R\x12cameraRoamingSpeed\x12*\n" +
	"\x11using_free_cursor\x18\b \x01(\bR\x0fusingFreeCursor\x121\n" +
	"\x13enemy_hero_aimed_at\x18\n" +
	" \x01(\x05:\x02-1R\x10enemyHeroAimedAt\x12 \n" +
	"\fview_delta_x\x18\v \x03(\x05R\n" +
	"viewDeltaX\x12 \n" +
	"\fview_delta_y\x18\f \x03(\x05R\n" +
	"viewDeltaY\x124\n" +
	"\x17is_in_third_person_view\x18\r \x01(\bR\x13isInThirdPersonViewB4Z2github.com/RyPort/paradox-parser/deadlock;deadlock"

var (
	file_citadel_usercmd_proto_rawDescOnce sync.Once
	file_citadel_usercmd_proto_rawDescData []byte
)

func file_citadel_usercmd_proto_rawDescGZIP() []byte {
	file_citadel_usercmd_proto_rawDescOnce.Do(func() {
		file_citadel_usercmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_citadel_usercmd_proto_rawDesc), len(file_citadel_usercmd_proto_rawDesc)))
	})
	return file_citadel_usercmd_proto_rawDescData
}

var file_citadel_usercmd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_citadel_usercmd_proto_goTypes = []any{
	(*CCitadelUserCmdPB)(nil), // 0: deadlock.CCitadelUserCmdPB
	(*CBaseUserCmdPB)(nil),    // 1: deadlock.CBaseUserCmdPB
	(*CMsgVector)(nil),        // 2: deadlock.CMsgVector
	(*CMsgQAngle)(nil),        // 3: deadlock.CMsgQAngle
}
var file_citadel_usercmd_proto_depIdxs = []int32{
	1, // 0: deadlock.CCitadelUserCmdPB.base:type_name -> deadlock.CBaseUserCmdPB
	2, // 1: deadlock.CCitadelUserCmdPB.vec_camera_position:type_name -> deadlock.CMsgVector
	3, // 2: deadlock.CCitadelUserCmdPB.ang_camera_angles:type_name -> deadlock.CMsgQAngle
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_citadel_usercmd_proto_init() }
func file_citadel_usercmd_proto_init() {
	if File_citadel_usercmd_proto != nil {
		return
	}
	file_networkbasetypes_proto_init()
	file_usercmd_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_citadel_usercmd_proto_rawDesc), len(file_citadel_usercmd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_citadel_usercmd_proto_goTypes,
		DependencyIndexes: file_citadel_usercmd_proto_depIdxs,
		MessageInfos:      file_citadel_usercmd_proto_msgTypes,
	}.Build()
	File_citadel_usercmd_proto = out.File
	file_citadel_usercmd_proto_goTypes = nil
	file_citadel_usercmd_proto_depIdxs = nil
}
