// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.6.1
// source: steammessages_oauth.steamworkssdk.proto

package deadlock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type COAuthToken_ImplicitGrantNoPrompt_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clientid      *string                `protobuf:"bytes,1,opt,name=clientid" json:"clientid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *COAuthToken_ImplicitGrantNoPrompt_Request) Reset() {
	*x = COAuthToken_ImplicitGrantNoPrompt_Request{}
	mi := &file_steammessages_oauth_steamworkssdk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *COAuthToken_ImplicitGrantNoPrompt_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*COAuthToken_ImplicitGrantNoPrompt_Request) ProtoMessage() {}

func (x *COAuthToken_ImplicitGrantNoPrompt_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_oauth_steamworkssdk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use COAuthToken_ImplicitGrantNoPrompt_Request.ProtoReflect.Descriptor instead.
func (*COAuthToken_ImplicitGrantNoPrompt_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_oauth_steamworkssdk_proto_rawDescGZIP(), []int{0}
}

func (x *COAuthToken_ImplicitGrantNoPrompt_Request) GetClientid() string {
	if x != nil && x.Clientid != nil {
		return *x.Clientid
	}
	return ""
}

type COAuthToken_ImplicitGrantNoPrompt_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	RedirectUri   *string                `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *COAuthToken_ImplicitGrantNoPrompt_Response) Reset() {
	*x = COAuthToken_ImplicitGrantNoPrompt_Response{}
	mi := &file_steammessages_oauth_steamworkssdk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *COAuthToken_ImplicitGrantNoPrompt_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*COAuthToken_ImplicitGrantNoPrompt_Response) ProtoMessage() {}

func (x *COAuthToken_ImplicitGrantNoPrompt_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_oauth_steamworkssdk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use COAuthToken_ImplicitGrantNoPrompt_Response.ProtoReflect.Descriptor instead.
func (*COAuthToken_ImplicitGrantNoPrompt_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_oauth_steamworkssdk_proto_rawDescGZIP(), []int{1}
}

func (x *COAuthToken_ImplicitGrantNoPrompt_Response) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *COAuthToken_ImplicitGrantNoPrompt_Response) GetRedirectUri() string {
	if x != nil && x.RedirectUri != nil {
		return *x.RedirectUri
	}
	return ""
}

var File_steammessages_oauth_steamworkssdk_proto protoreflect.FileDescriptor

const file_steammessages_oauth_steamworkssdk_proto_rawDesc = "" +
	"\n" +
	"'steammessages_oauth.steamworkssdk.proto\x12\bdeadlock\x1a.steammessages_unified_base.steamworkssdk.proto\"\x85\x01\n" +
	")COAuthToken_ImplicitGrantNoPrompt_Request\x12X\n" +
	"\bclientid\x18\x01 \x01(\tB<\x82\xb5\x188Client ID for which to count the number of issued tokensR\bclientid\"\xd1\x01\n" +
	"*COAuthToken_ImplicitGrantNoPrompt_Response\x12F\n" +
	"\faccess_token\x18\x01 \x01(\tB#\x82\xb5\x18\x1fOAuth Token, granted on successR\vaccessToken\x12[\n" +
	"\fredirect_uri\x18\x02 \x01(\tB8\x82\xb5\x184Redirection URI provided during client registration.R\vredirectUri2\xc3\x02\n" +
	"\n" +
	"OAuthToken\x12\xfd\x01\n" +
	"\x15ImplicitGrantNoPrompt\x123.deadlock.COAuthToken_ImplicitGrantNoPrompt_Request\x1a4.deadlock.COAuthToken_ImplicitGrantNoPrompt_Response\"y\x82\xb5\x18uGrants an implicit OAuth token (grant type 'token') for the specified client ID on behalf of a user without prompting\x1a5\x82\xb5\x181Service containing methods to manage OAuth tokensB4Z2github.com/RyPort/paradox-parser/deadlock;deadlock"

var (
	file_steammessages_oauth_steamworkssdk_proto_rawDescOnce sync.Once
	file_steammessages_oauth_steamworkssdk_proto_rawDescData []byte
)

func file_steammessages_oauth_steamworkssdk_proto_rawDescGZIP() []byte {
	file_steammessages_oauth_steamworkssdk_proto_rawDescOnce.Do(func() {
		file_steammessages_oauth_steamworkssdk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_oauth_steamworkssdk_proto_rawDesc), len(file_steammessages_oauth_steamworkssdk_proto_rawDesc)))
	})
	return file_steammessages_oauth_steamworkssdk_proto_rawDescData
}

var file_steammessages_oauth_steamworkssdk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steammessages_oauth_steamworkssdk_proto_goTypes = []any{
	(*COAuthToken_ImplicitGrantNoPrompt_Request)(nil),  // 0: deadlock.COAuthToken_ImplicitGrantNoPrompt_Request
	(*COAuthToken_ImplicitGrantNoPrompt_Response)(nil), // 1: deadlock.COAuthToken_ImplicitGrantNoPrompt_Response
}
var file_steammessages_oauth_steamworkssdk_proto_depIdxs = []int32{
	0, // 0: deadlock.OAuthToken.ImplicitGrantNoPrompt:input_type -> deadlock.COAuthToken_ImplicitGrantNoPrompt_Request
	1, // 1: deadlock.OAuthToken.ImplicitGrantNoPrompt:output_type -> deadlock.COAuthToken_ImplicitGrantNoPrompt_Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steammessages_oauth_steamworkssdk_proto_init() }
func file_steammessages_oauth_steamworkssdk_proto_init() {
	if File_steammessages_oauth_steamworkssdk_proto != nil {
		return
	}
	file_steammessages_unified_base_steamworkssdk_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_oauth_steamworkssdk_proto_rawDesc), len(file_steammessages_oauth_steamworkssdk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steammessages_oauth_steamworkssdk_proto_goTypes,
		DependencyIndexes: file_steammessages_oauth_steamworkssdk_proto_depIdxs,
		MessageInfos:      file_steammessages_oauth_steamworkssdk_proto_msgTypes,
	}.Build()
	File_steammessages_oauth_steamworkssdk_proto = out.File
	file_steammessages_oauth_steamworkssdk_proto_goTypes = nil
	file_steammessages_oauth_steamworkssdk_proto_depIdxs = nil
}
